import { Prisma } from '../../../prisma/generated/client';
import { SessionStatus } from '../../../prisma/generated/enums';

export type EventSessionListScope = 'today' | 'upcoming' | 'history';

export function startOfUtcDay(d: Date): Date {
  return new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate(), 0, 0, 0, 0));
}

export function endOfUtcDay(d: Date): Date {
  const s = startOfUtcDay(d);
  return new Date(s.getTime() + 86400000 - 1);
}

export function addUtcDays(d: Date, days: number): Date {
  const x = new Date(d.getTime());
  x.setUTCDate(x.getUTCDate() + days);
  return x;
}

export function sessionOverlapsRange(
  registrationDate: Date,
  deadline: Date,
  rangeStart: Date,
  rangeEnd: Date
): boolean {
  return registrationDate.getTime() <= rangeEnd.getTime() && deadline.getTime() >= rangeStart.getTime();
}

export type SessionForActivePick = {
  id: string;
  status: SessionStatus;
  registrationDate: Date;
  deadline: Date;
  /** When maintained, this row is the canonical “show this session” for the event. */
  isCurrentSession?: boolean;
};

/** Fields used by event detail `eventSession` selection. */
export type SessionForDetailPick = SessionForActivePick & {
  autoGenerated?: boolean;
  createdAt?: Date;
};

export function pickActiveEventSession<T extends SessionForActivePick>(
  sessions: T[],
  now: Date = new Date()
): T | null {
  if (!sessions.length) return null;
  const list = sessions.filter(s => s.status !== SessionStatus.Cancelled);
  if (!list.length) return null;

  const marked = list.filter(s => s.isCurrentSession);
  if (marked.length === 1) return marked[0];
  if (marked.length > 1) {
    return [...marked].sort((a, b) => b.deadline.getTime() - a.deadline.getTime())[0];
  }

  const ongoing = list.find(s => s.status === SessionStatus.Ongoing);
  if (ongoing) return ongoing;

  const inWindow = list.filter(
    s => s.registrationDate.getTime() <= now.getTime() && s.deadline.getTime() >= now.getTime()
  );
  const published = inWindow.find(s => s.status === SessionStatus.Published);
  if (published) return published;
  const unverified = inWindow.find(s => s.status === SessionStatus.Unverified);
  if (unverified) return unverified;

  const future = list
    .filter(s => s.deadline.getTime() >= now.getTime())
    .sort((a, b) => a.registrationDate.getTime() - b.registrationDate.getTime());
  if (future.length) return future[0];

  const past = list
    .filter(
      s => s.deadline.getTime() < now.getTime() || s.status === SessionStatus.Completed
    )
    .sort((a, b) => b.deadline.getTime() - a.deadline.getTime());
  return past[0] ?? list[0];
}


export function pickEventSessionForDetail<T extends SessionForDetailPick>(
  sessions: T[],
  now: Date = new Date()
): T | null {
  if (!sessions.length) return null;

  const eligible = sessions.filter(s => s.status !== SessionStatus.Cancelled);
  if (!eligible.length) return null;

  const flagged = eligible.filter(s => s.isCurrentSession);
  if (flagged.length === 1) return flagged[0];
  if (flagged.length > 1) {
    return [...flagged].sort((a, b) => b.deadline.getTime() - a.deadline.getTime())[0];
  }

  const upcoming = eligible.filter(
    s =>
      s.status !== SessionStatus.Completed &&
      s.deadline.getTime() >= now.getTime()
  );
  if (upcoming.length) {
    const ongoing = upcoming.find(s => s.status === SessionStatus.Ongoing);
    if (ongoing) return ongoing;
    return [...upcoming].sort((a, b) => a.deadline.getTime() - b.deadline.getTime())[0];
  }

  const auto = eligible.filter(s => s.autoGenerated);
  if (auto.length) {
    const autoFuture = auto.filter(s => s.deadline.getTime() >= now.getTime());
    const autoPick = autoFuture.length ? autoFuture : auto;
    const og = autoPick.find(s => s.status === SessionStatus.Ongoing);
    if (og) return og;
    if (autoFuture.length) {
      return [...autoFuture].sort((a, b) => a.deadline.getTime() - b.deadline.getTime())[0];
    }
    return [...autoPick].sort((a, b) => {
      const ca = a.createdAt?.getTime() ?? 0;
      const cb = b.createdAt?.getTime() ?? 0;
      if (cb !== ca) return cb - ca;
      return b.deadline.getTime() - a.deadline.getTime();
    })[0];
  }

  const ended = eligible.filter(
    s => s.status === SessionStatus.Completed || s.deadline.getTime() < now.getTime()
  );
  if (ended.length) {
    return [...ended].sort((a, b) => b.deadline.getTime() - a.deadline.getTime())[0];
  }

  return [...eligible].sort((a, b) => b.deadline.getTime() - a.deadline.getTime())[0];
}


export function sessionScopeWhereInput(
  scope: EventSessionListScope,
  now: Date = new Date()
): Prisma.EventSessionWhereInput {
  const startToday = startOfUtcDay(now);
  const endToday = endOfUtcDay(now);
  const startTomorrow = startOfUtcDay(addUtcDays(now, 1));

  switch (scope) {
    case 'today':
      return {
        AND: [
          { registrationDate: { lte: endToday } },
          { deadline: { gte: startToday } },
          { status: { notIn: [SessionStatus.Cancelled] } },
        ],
      };
    case 'upcoming':
      return {
        AND: [
          { deadline: { gte: startTomorrow } },
          { status: { notIn: [SessionStatus.Completed, SessionStatus.Cancelled] } },
        ],
      };
    case 'history':
      return {
        OR: [
          { deadline: { lt: startToday } },
          { status: SessionStatus.Completed },
        ],
      };
    default:
      return {};
  }
}

export function priceRangeOnSession(
  priceMin?: string | number | null,
  priceMax?: string | number | null
): Prisma.EventSessionWhereInput | null {
  if (priceMin == null && priceMax == null) return null;
  const cost: { gte?: Prisma.Decimal; lte?: Prisma.Decimal } = {};
  if (priceMin != null && priceMin !== '') {
    cost.gte = new Prisma.Decimal(String(priceMin));
  }
  if (priceMax != null && priceMax !== '') {
    cost.lte = new Prisma.Decimal(String(priceMax));
  }
  return Object.keys(cost).length ? { cost } : null;
}
