import { PaginationOptions } from '../../interfaces';
import {
  CompetitionLevel,
  EventType,
  GroupCriteria,
  RepeatFrequency,
  RoundCondition,
  SessionBucketType,
  SessionStatus,
} from '../../../prisma/generated/enums';

export const EVENT_CONTRIBUTION_SCORE = {
  CREATE: 10,
  UPDATE: 5,
  VERIFY: 15,
  APPLY: 3,
} as const;

/** Matches Prisma model `RepeatConfig` */
export interface IRepeatConfigInput {
  repeatFunction?: RepeatFrequency;
  startDate?: Date | string;
}

/** Matches Prisma model `EventRound` */
export interface IEventRoundInput {
  roundType: CompetitionLevel;
  deadline: Date | string;
  cost: string | number;
  hasFinalDeadline?: boolean;
  finalDeadline?: Date | string | null;
  lateFee?: string | number;
  description?: string | null;
}

export interface IEventGroupInput {
  name: string;
  criteria: GroupCriteria;
  condition: RoundCondition;
  value: number;
  rounds?: IEventRoundInput[];
}

export interface IEventSessionInput {
  sessionId?: string;
  year?: string;
  /** Session category/type (Daily/Weekly/Monthly/Quarterly/Yearly/Custom). */
  session?: SessionBucketType | null;
  /** Session label value (Q1/January/Sunday/Week1/Year). */
  sessionValue?: string | null;
  sessionLevel?: string | null;
  competitionLevel: CompetitionLevel;
  eventType: EventType;
  registrationDate: Date | string;
  deadline: Date | string;
  cost: string | number;
  hasFinalDeadline?: boolean;
  finalDeadline?: Date | string | null;
  lateFee?: string | number;
  status?: SessionStatus;
  isSharedToCommunity?: boolean;
  isUserAgreementAccepted?: boolean;
  groups?: IEventGroupInput[];
}


export interface ICreateEventPayload {
  eventName: string;
  coverImage?: string;
  programId: string;
  organizer: string;
  location?: string | null;
  eventPortal: string;
  registrationPortal: string;
  description: string;
  note?: string | null;
  isPublished?: boolean;
  repeatConfig?: IRepeatConfigInput | null;
  eventSession?: IEventSessionInput;
}
export interface IUpdateCurrentEventSessionPayload {
  competitionLevel?: CompetitionLevel;
  eventType?: EventType;
  registrationDate?: Date | string;
  deadline?: Date | string;
  cost?: string | number;
  hasFinalDeadline?: boolean;
  finalDeadline?: Date | string | null;
  lateFee?: string | number;
  status?: SessionStatus;
  isSharedToCommunity?: boolean;
  isUserAgreementAccepted?: boolean;
  autoGenerated?: boolean;
}

export interface IUpdateEventPayload {
  eventName?: string;
  coverImage?: string;
  programId?: string;
  organizer?: string;
  location?: string | null;
  eventPortal?: string;
  registrationPortal?: string;
  description?: string;
  note?: string | null;
  isPublished?: boolean;
  isActive?: boolean;
  repeatConfig?: IRepeatConfigInput | null;
  currentEventSession?: IUpdateCurrentEventSessionPayload;
  isVerifyActive?: boolean;
}

export type EventSessionScopeFilter = 'today' | 'upcoming' | 'history';

export interface IEventFilters {
  search?: string;
  programId?: string;
  eventType?: EventType;
  location?: string;
  groupCriteria?: GroupCriteria;
  timeRangeFrom?: string;
  timeRangeTo?: string;
  /** Filter events that have at least one session in this bucket (UTC); combine with priceMin/priceMax on sessions. */
  sessionScope?: EventSessionScopeFilter;
  priceMin?: string;
  priceMax?: string;
}

export interface IFeedPriceFilters {
  priceMin?: string;
  priceMax?: string;
}

export interface IEventQuery {
  filters: IEventFilters;
  options: PaginationOptions;
}
