import { Prisma } from '../../../prisma/generated/client';
import { RepeatFrequency, SessionBucketType, SessionStatus } from '../../../prisma/generated/enums';
import { database } from '../../config/database';
import { IEventGroupInput, IRepeatConfigInput } from './event.interface';
import { pickActiveEventSession } from './event.helpers';

export const toDecimal = (value: string | number | undefined | null): Prisma.Decimal => {
  if (value === undefined || value === null || value === '') {
    return new Prisma.Decimal(0);
  }
  return new Prisma.Decimal(String(value));
};

export const eventGroupsToNestedCreate = (groups: IEventGroupInput[] | undefined) => {
  if (!groups?.length) {
    return undefined;
  }
  return {
    create: groups.map(g => ({
      name: g.name,
      criteria: g.criteria,
      condition: g.condition,
      value: g.value,
      rounds: g.rounds?.length
        ? {
            create: g.rounds.map(r => ({
              roundType: r.roundType,
              deadline: new Date(r.deadline),
              cost: toDecimal(r.cost),
              hasFinalDeadline: r.hasFinalDeadline ?? false,
              finalDeadline: r.finalDeadline ? new Date(r.finalDeadline) : null,
              lateFee: toDecimal(r.lateFee ?? 0),
              description: r.description ?? null,
            })),
          }
        : undefined,
    })),
  };
};

const addDays = (base: Date, days: number) => new Date(base.getTime() + days * 86400000);
const addMonths = (base: Date, months: number) => {
  const d = new Date(base.getTime());
  d.setUTCMonth(d.getUTCMonth() + months);
  return d;
};
const addYears = (base: Date, years: number) => {
  const d = new Date(base.getTime());
  d.setUTCFullYear(d.getUTCFullYear() + years);
  return d;
};

const MONTH_FULL = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
] as const;

const WEEKDAY_NAME_EN = [
  'Sunday',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
] as const;

const weekOfYearUtc = (date: Date) => {
  const start = new Date(Date.UTC(date.getUTCFullYear(), 0, 1));
  const diffDays = Math.floor((date.getTime() - start.getTime()) / 86400000);
  return Math.floor(diffDays / 7) + 1;
};

export const resolveRepeatFrequency = (input?: IRepeatConfigInput | null): RepeatFrequency =>
  input?.repeatFunction ?? RepeatFrequency.DontRepeat;

export const sessionTypeFromRepeatFrequency = (
  frequency: RepeatFrequency
): SessionBucketType => {
  switch (frequency) {
    case RepeatFrequency.Daily:
      return SessionBucketType.Daily;
    case RepeatFrequency.Weekly:
      return SessionBucketType.Weekly;
    case RepeatFrequency.Monthly:
      return SessionBucketType.Monthly;
    case RepeatFrequency.Quarterly:
      return SessionBucketType.Quarterly;
    case RepeatFrequency.Yearly:
      return SessionBucketType.Yearly;
    case RepeatFrequency.Custom:
      return SessionBucketType.Custom;
    case RepeatFrequency.DontRepeat:
    default:
      return SessionBucketType.Custom;
  }
};

export const frequencySuffix = (frequency: RepeatFrequency, anchorDate: Date) => {
  switch (frequency) {
    case RepeatFrequency.Daily:
      return WEEKDAY_NAME_EN[anchorDate.getUTCDay()] ?? 'Day';
    case RepeatFrequency.Weekly:
      return `Week${weekOfYearUtc(anchorDate)}`;
    case RepeatFrequency.Monthly:
      return MONTH_FULL[anchorDate.getUTCMonth()];
    case RepeatFrequency.Quarterly:
      return `Q${Math.floor(anchorDate.getUTCMonth() / 3) + 1}`;
    case RepeatFrequency.Yearly:
      return 'Year';
    case RepeatFrequency.Custom:
      return WEEKDAY_NAME_EN[anchorDate.getUTCDay()] ?? 'Day';
    default:
      return 'Session1';
  }
};

export const extractEventNameParts = (fullEventName: string, baseEventName: string) => {
  const normalizedBase = baseEventName.trim();
  const prefix = `${normalizedBase}-`;
  if (!fullEventName.startsWith(prefix)) {
    return { eventYear: null as string | null, eventSessionLabel: null as string | null };
  }
  const suffix = fullEventName.slice(prefix.length);
  const [eventYear, ...rest] = suffix.split('-');
  const eventSessionLabel = rest.join('-') || null;
  return {
    eventYear: eventYear || null,
    eventSessionLabel,
  };
};

const computeNextAutoGenerateDate = (input: IRepeatConfigInput): Date | null => {
  const frequency = resolveRepeatFrequency(input);
  if (frequency === RepeatFrequency.DontRepeat) return null;

  const base = input.startDate ? new Date(input.startDate) : new Date();

  switch (frequency) {
    case RepeatFrequency.Daily:
      return addDays(base, 1);
    case RepeatFrequency.Weekly:
      return addDays(base, 7);
    case RepeatFrequency.Monthly:
      return addMonths(base, 1);
    case RepeatFrequency.Quarterly:
      return addMonths(base, 3);
    case RepeatFrequency.Yearly:
      return addYears(base, 1);
    case RepeatFrequency.Custom:
      return addDays(base, 1);
    default:
      return null;
  }
};

export const repeatConfigFields = (input: IRepeatConfigInput) => ({
  frequency: resolveRepeatFrequency(input),
  startDate: input.startDate ? new Date(input.startDate) : null,
  nextAutoGenerateDate: computeNextAutoGenerateDate(input),
});

export const eventListSelect = {
  id: true,
  eventName: true,
  coverImage: true,
  programId: true,
  organizer: true,
  location: true,
  isPublished: true,
  isActive: true,
  createdAt: true,
  updatedAt: true,
  program: { select: { id: true, name: true, imageUrl: true } },
} as const;

export const publishedEventBaseWhere = {
  deletedAt: null,
  isActive: true,
  isPublished: true,
} as const;

const eventSessionForActivePickSelect = {
  eventId: true,
  id: true,
  status: true,
  registrationDate: true,
  deadline: true,
  cost: true,
  eventType: true,
  competitionLevel: true,
  session: {
    select: {
      id: true,
      session: true,
      sessionValue: true,
      sessionLevel: true,
      year: true,
      creationMode: true
    },
  },
} as const;

type EventSessionForActiveRow = Prisma.EventSessionGetPayload<{
  select: typeof eventSessionForActivePickSelect;
}>;

async function sessionsByEventIdMap(eventIds: string[]) {
  const map = new Map<string, EventSessionForActiveRow[]>();
  if (!eventIds.length) return map;
  const rows = await database.eventSession.findMany({
    where: { eventId: { in: eventIds } },
    select: eventSessionForActivePickSelect,
    orderBy: { deadline: 'asc' as const },
  });
  for (const r of rows) {
    const arr = map.get(r.eventId) ?? [];
    arr.push(r);
    map.set(r.eventId, arr);
  }
  return map;
}

export async function attachActiveSessions<T extends { id: string }>(events: T[]) {
  const map = await sessionsByEventIdMap(events.map(e => e.id));
  return events.map(e => ({
    ...e,
    eventSession: (() => {
      const picked = pickActiveEventSession(map.get(e.id) ?? []);
      return picked ?? null;
    })(),
  }));
}

export const sessionIncludeWithYearLevel = {
  id: true,
  session: true,
  sessionValue: true,
  sessionLevel: true,
  year: true,
  creationMode: true,
} as const;

export const eventSessionIncludeWithMeta = {
  session: {
    select: sessionIncludeWithYearLevel,
  },
  groups: { include: { rounds: true } },
} as const;

export const eventSessionForVerifyInclude = {
  session: {
    select: sessionIncludeWithYearLevel,
  },
  groups: { include: { rounds: true } },
} as const;

export const statusNotCancelledFilter = { notIn: [SessionStatus.Cancelled] } as const;
