import { Prisma } from '../../../prisma/generated/client';
import { RepeatFrequency, SessionBucketFormat, SessionStatus } from '../../../prisma/generated/enums';
import type { IUpdateEventPayload, IUpdateCurrentEventSessionPayload } from './event.interface';
import type { EventAuditSnapshot } from './event.repository';

const MONTH_MMM = [
  'JAN',
  'FEB',
  'MAR',
  'APR',
  'MAY',
  'JUN',
  'JUL',
  'AUG',
  'SEP',
  'OCT',
  'NOV',
  'DEC',
] as const;

const EDIT_LOG_SCALAR_FIELDS = [
  'programId',
  'organizer',
  'location',
  'eventPortal',
  'registrationPortal',
  'description',
  'note',
  'isPublished',
  'isActive',
  'isLocked',
  'coverImage',
] as const;

const pad2 = (n: number) => String(n).padStart(2, '0');

export type EventEditLogPayload = {
  newVersion: number;
  changedFields: string[];
  previousValues: Prisma.InputJsonValue;
};

export type EventSessionListScope = 'today' | 'upcoming' | 'history';

export type SessionForActivePick = {
  id: string;
  status: SessionStatus;
  registrationDate: Date;
  deadline: Date;
  isCurrentSession?: boolean;
};

export type SessionForDetailPick = SessionForActivePick & {
  autoGenerated?: boolean;
  createdAt?: Date;
};

export type BuildSessionIdentifierParams = {
  year: string;
  format: SessionBucketFormat;
  quarter?: number | null;
  month?: number | null;
  anchorDate?: Date | null;
};

const toJsonColumnValue = (value: unknown): Prisma.InputJsonValue =>
  JSON.parse(
    JSON.stringify(value, (_k, val) => (typeof val === 'bigint' ? val.toString() : val))
  ) as Prisma.InputJsonValue;

const sameScalar = (before: unknown, after: unknown): boolean => {
  if (before === after) return true;
  if (before == null && after == null) return true;
  if (before == null || after == null) return false;
  if (typeof before === 'object' && typeof after === 'object' && before && after) {
    if ('equals' in before && typeof (before as { equals?: (x: unknown) => boolean }).equals === 'function') {
      try {
        return Boolean((before as { equals: (x: unknown) => boolean }).equals(after));
      } catch {
        return String(before) === String(after);
      }
    }
  }
  return false;
};

const sameRepeatJson = (before: unknown, incoming: unknown): boolean => {
  try {
    return JSON.stringify(before ?? null) === JSON.stringify(incoming ?? null);
  } catch {
    return false;
  }
};

function formatIsoWeekLabel(d: Date): string {
  const t = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
  const day = t.getUTCDay() || 7;
  t.setUTCDate(t.getUTCDate() + 4 - day);
  const isoYear = t.getUTCFullYear();
  const yearStart = new Date(Date.UTC(isoYear, 0, 1));
  const week = Math.ceil(((t.getTime() - yearStart.getTime()) / 86400000 + 1) / 7) || 1;
  return `${isoYear}-W${pad2(week)}`;
}

const calendarYearFromLabel = (yearLabel: string): number | null => {
  const n = parseInt(yearLabel.trim(), 10);
  if (!Number.isFinite(n) || n < 1000 || n > 9999) return null;
  return n;
};

export function diffEventForEditLog(args: {
  before: EventAuditSnapshot;
  scalarPatch: Record<string, unknown>;
  repeatInPayload: boolean;
  incomingRepeat: IUpdateEventPayload['repeatConfig'];
  sessionPatchRequested: boolean;
}): EventEditLogPayload | null {
  const changedFields: string[] = [];
  const previousValues: Record<string, unknown> = {};

  for (const key of EDIT_LOG_SCALAR_FIELDS) {
    if (!(key in args.scalarPatch)) continue;
    const nextVal = args.scalarPatch[key];
    const prevVal = args.before[key];
    if (!sameScalar(prevVal, nextVal)) {
      changedFields.push(key);
      previousValues[key] = prevVal ?? null;
    }
  }

  if (args.repeatInPayload && !sameRepeatJson(args.before.repeatConfig, args.incomingRepeat)) {
    changedFields.push('repeatConfig');
    previousValues.repeatConfig = args.before.repeatConfig ?? null;
  }

  if (args.sessionPatchRequested) {
    changedFields.push('currentEventSession');
    previousValues.currentEventSession = args.before.eventSessions[0] ?? null;
  }

  if (!changedFields.length) return null;

  return {
    changedFields,
    previousValues: toJsonColumnValue(previousValues),
    newVersion: args.before.version + 1,
  };
}

export function startOfUtcDay(d: Date): Date {
  return new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate(), 0, 0, 0, 0));
}

export function endOfUtcDay(d: Date): Date {
  const s = startOfUtcDay(d);
  return new Date(s.getTime() + 86400000 - 1);
}

export function addUtcDays(d: Date, days: number): Date {
  const x = new Date(d.getTime());
  x.setUTCDate(x.getUTCDate() + days);
  return x;
}

export function pickActiveEventSession<T extends SessionForActivePick>(
  sessions: T[],
  now: Date = new Date()
): T | null {
  if (!sessions.length) return null;
  const list = sessions.filter(s => s.status !== SessionStatus.Cancelled);
  if (!list.length) return null;

  const marked = list.filter(s => s.isCurrentSession);
  if (marked.length === 1) return marked[0];
  if (marked.length > 1) {
    return [...marked].sort((a, b) => b.deadline.getTime() - a.deadline.getTime())[0];
  }

  const ongoing = list.find(s => s.status === SessionStatus.Ongoing);
  if (ongoing) return ongoing;

  const inWindow = list.filter(
    s => s.registrationDate.getTime() <= now.getTime() && s.deadline.getTime() >= now.getTime()
  );
  const published = inWindow.find(s => s.status === SessionStatus.Published);
  if (published) return published;
  const unverified = inWindow.find(s => s.status === SessionStatus.Unverified);
  if (unverified) return unverified;

  const future = list
    .filter(s => s.deadline.getTime() >= now.getTime())
    .sort((a, b) => a.registrationDate.getTime() - b.registrationDate.getTime());
  if (future.length) return future[0];

  const past = list
    .filter(s => s.deadline.getTime() < now.getTime() || s.status === SessionStatus.Completed)
    .sort((a, b) => b.deadline.getTime() - a.deadline.getTime());
  return past[0] ?? list[0];
}

export function pickEventSessionForDetail<T extends SessionForDetailPick>(
  sessions: T[],
  now: Date = new Date()
): T | null {
  if (!sessions.length) return null;

  const eligible = sessions.filter(s => s.status !== SessionStatus.Cancelled);
  if (!eligible.length) return null;

  const flagged = eligible.filter(s => s.isCurrentSession);
  if (flagged.length === 1) return flagged[0];
  if (flagged.length > 1) {
    return [...flagged].sort((a, b) => b.deadline.getTime() - a.deadline.getTime())[0];
  }

  const upcoming = eligible.filter(
    s => s.status !== SessionStatus.Completed && s.deadline.getTime() >= now.getTime()
  );
  if (upcoming.length) {
    const ongoing = upcoming.find(s => s.status === SessionStatus.Ongoing);
    if (ongoing) return ongoing;
    return [...upcoming].sort((a, b) => a.deadline.getTime() - b.deadline.getTime())[0];
  }

  const auto = eligible.filter(s => s.autoGenerated);
  if (auto.length) {
    const autoFuture = auto.filter(s => s.deadline.getTime() >= now.getTime());
    const autoPick = autoFuture.length ? autoFuture : auto;
    const og = autoPick.find(s => s.status === SessionStatus.Ongoing);
    if (og) return og;
    if (autoFuture.length) {
      return [...autoFuture].sort((a, b) => a.deadline.getTime() - b.deadline.getTime())[0];
    }
    return [...autoPick].sort((a, b) => {
      const ca = a.createdAt?.getTime() ?? 0;
      const cb = b.createdAt?.getTime() ?? 0;
      if (cb !== ca) return cb - ca;
      return b.deadline.getTime() - a.deadline.getTime();
    })[0];
  }

  const ended = eligible.filter(
    s => s.status === SessionStatus.Completed || s.deadline.getTime() < now.getTime()
  );
  if (ended.length) {
    return [...ended].sort((a, b) => b.deadline.getTime() - a.deadline.getTime())[0];
  }

  return [...eligible].sort((a, b) => b.deadline.getTime() - a.deadline.getTime())[0];
}

export function sessionScopeWhereInput(
  scope: EventSessionListScope,
  now: Date = new Date()
): Prisma.EventSessionWhereInput {
  const startToday = startOfUtcDay(now);
  const endToday = endOfUtcDay(now);
  const startTomorrow = startOfUtcDay(addUtcDays(now, 1));

  switch (scope) {
    case 'today':
      return {
        AND: [
          { registrationDate: { lte: endToday } },
          { deadline: { gte: startToday } },
          { status: { notIn: [SessionStatus.Cancelled] } },
        ],
      };
    case 'upcoming':
      return {
        AND: [
          { deadline: { gte: startTomorrow } },
          { status: { notIn: [SessionStatus.Completed, SessionStatus.Cancelled] } },
        ],
      };
    case 'history':
      return {
        OR: [{ deadline: { lt: startToday } }, { status: SessionStatus.Completed }],
      };
    default:
      return {};
  }
}

export function priceRangeOnSession(
  priceMin?: string | number | null,
  priceMax?: string | number | null
): Prisma.EventSessionWhereInput | null {
  if (priceMin == null && priceMax == null) return null;
  const cost: { gte?: Prisma.Decimal; lte?: Prisma.Decimal } = {};
  if (priceMin != null && priceMin !== '') {
    cost.gte = new Prisma.Decimal(String(priceMin));
  }
  if (priceMax != null && priceMax !== '') {
    cost.lte = new Prisma.Decimal(String(priceMax));
  }
  return Object.keys(cost).length ? { cost } : null;
}

export function hasCurrentSessionPatchBody(
  body: IUpdateCurrentEventSessionPayload | undefined
): body is IUpdateCurrentEventSessionPayload {
  return Boolean(body && typeof body === 'object' && Object.keys(body).length > 0);
}

export function defaultSessionBucketFormat(
  repeatFrequency?: RepeatFrequency | null
): SessionBucketFormat {
  switch (repeatFrequency) {
    case RepeatFrequency.Monthly:
      return SessionBucketFormat.Year_MMM;
    case RepeatFrequency.Quarterly:
      return SessionBucketFormat.Year_Q;
    case RepeatFrequency.Yearly:
      return SessionBucketFormat.Year_Only;
    case RepeatFrequency.Weekly:
      return SessionBucketFormat.Year_ISOWeek;
    case RepeatFrequency.Daily:
      return SessionBucketFormat.Year_Month_Day;
    case RepeatFrequency.Custom:
      return SessionBucketFormat.Year_MM;
    case RepeatFrequency.DontRepeat:
    default:
      return SessionBucketFormat.Year_Only;
  }
}

export function buildSessionIdentifier(params: BuildSessionIdentifierParams): string {
  const y = params.year.trim();
  const now = new Date();
  const yNum = calendarYearFromLabel(y);

  switch (params.format) {
    case SessionBucketFormat.Year_Only:
      return y;
    case SessionBucketFormat.Year_Q: {
      const ref = params.anchorDate ?? (yNum !== null ? new Date(Date.UTC(yNum, 0, 15)) : now);
      const q =
        params.quarter ??
        (Number.isFinite(ref.getMonth()) ? Math.floor(ref.getMonth() / 3) + 1 : 1);
      const clamped = Math.min(4, Math.max(1, q));
      return `${y}-Q${clamped}`;
    }
    case SessionBucketFormat.Year_MMM: {
      const m =
        params.month ??
        (params.anchorDate ? params.anchorDate.getMonth() + 1 : yNum !== null ? 1 : now.getMonth() + 1);
      const clamped = Math.min(12, Math.max(1, m));
      return `${y}-${MONTH_MMM[clamped - 1]}`;
    }
    case SessionBucketFormat.Year_MM: {
      const m =
        params.month ??
        (params.anchorDate ? params.anchorDate.getMonth() + 1 : yNum !== null ? 1 : now.getMonth() + 1);
      const clamped = Math.min(12, Math.max(1, m));
      return `${y}-${pad2(clamped)}`;
    }
    case SessionBucketFormat.Year_Month_Day: {
      if (params.anchorDate) {
        const d = params.anchorDate;
        return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`;
      }
      if (yNum !== null) {
        return `${yNum}-01-01`;
      }
      const d = now;
      return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`;
    }
    case SessionBucketFormat.Year_ISOWeek: {
      const ref = params.anchorDate ?? (yNum !== null ? new Date(Date.UTC(yNum, 0, 4)) : now);
      return formatIsoWeekLabel(ref);
    }
    default:
      return y;
  }
}

const toFiniteNumber = (value: unknown): number => {
  if (value == null) return 0;
  if (typeof value === 'number') return Number.isFinite(value) ? value : 0;
  if (typeof value === 'string') {
    const n = Number(value);
    return Number.isFinite(n) ? n : 0;
  }
  if (typeof value === 'object' && value && 'toNumber' in value) {
    try {
      const n = (value as { toNumber: () => number }).toNumber();
      return Number.isFinite(n) ? n : 0;
    } catch {
      return 0;
    }
  }
  return 0;
};

export function withEventSessionCostEstimation<
  T extends {
    cost?: unknown;
    groups?: Array<{
      rounds?: Array<{ cost?: unknown }>;
    }>;
  },
>(session: T): T & {
  estimatedCost: {
    competitionLevelCost: number;
    roundsTotalCost: number;
    groupsTotalCost: number;
    totalEstimatedCost: number;
  };
  groups?: Array<
    NonNullable<T['groups']>[number] & {
      totalRoundCost: number;
    }
  >;
} {
  const baseCost = toFiniteNumber(session.cost);
  const groups = (session.groups ?? []).map(g => {
    const totalRoundCost = (g.rounds ?? []).reduce((sum, r) => sum + toFiniteNumber(r.cost), 0);
    return {
      ...g,
      totalRoundCost,
    };
  });
  const roundsTotalCost = groups.reduce((sum, g) => sum + g.totalRoundCost, 0);
  return {
    ...session,
    groups: groups as any,
    estimatedCost: {
      competitionLevelCost: baseCost,
      roundsTotalCost,
      groupsTotalCost: roundsTotalCost,
      totalEstimatedCost: baseCost + roundsTotalCost,
    },
  };
}
