import { randomUUID } from 'crypto';
import { Prisma } from '../../../prisma/generated/client';
import {
  EventApplicationStatus,
  PlacementType,
  RepeatEndType,
  RepeatFrequency,
  RepeatUnit,
  SessionStatus,
} from '../../../prisma/generated/enums';
import { database } from '../../config/database';
import {
  createPaginationQuery,
  createPaginationResult,
  PaginationOptions,
  PaginationResult,
  parsePaginationOptions,
} from '../../utils/paginate';
import {
  ICalendarDayFilters,
  ICalendarMonthFilters,
  ICreateEventPayload,
  IEventFilters,
  IEventGroupInput,
  IFeedPriceFilters,
  IRepeatConfigInput,
  IUpdateCurrentEventSessionPayload,
} from './event.interface';
import { buildSessionIdentifier, defaultSessionBucketFormat } from './sessionBucket.util';
import {
  addUtcDays,
  endOfUtcDay,
  pickActiveEventSession,
  priceRangeOnSession,
  sessionScopeWhereInput,
  startOfUtcDay,
} from './eventSessionScope.util';

const toDecimal = (value: string | number | undefined | null): Prisma.Decimal => {
  if (value === undefined || value === null || value === '') {
    return new Prisma.Decimal(0);
  }
  return new Prisma.Decimal(String(value));
};

const buildEventGroupsNestedCreate = (groups: IEventGroupInput[] | undefined) => {
  if (!groups?.length) {
    return undefined;
  }
  return {
    create: groups.map(g => ({
      name: g.name,
      criteria: g.criteria,
      condition: g.condition,
      value: g.value,
      rounds: g.rounds?.length
        ? {
            create: g.rounds.map(r => ({
              roundType: r.roundType,
              deadline: new Date(r.deadline),
              cost: toDecimal(r.cost),
              hasFinalDeadline: r.hasFinalDeadline ?? false,
              finalDeadline: r.finalDeadline ? new Date(r.finalDeadline) : null,
              lateFee: toDecimal(r.lateFee ?? 0),
              description: r.description ?? null,
            })),
          }
        : undefined,
    })),
  };
};

const repeatConfigFields = (input: IRepeatConfigInput) => ({
  frequency: input.frequency ?? RepeatFrequency.DontRepeat,
  startDate: input.startDate ? new Date(input.startDate) : null,
  interval: input.interval ?? 1,
  unit: input.unit ?? null,
  weekDays: input.weekDays ?? [],
  monthDay: input.monthDay ?? null,
  monthWeek: input.monthWeek ?? null,
  monthWeekDay: input.monthWeekDay ?? null,
  endType: input.endType ?? RepeatEndType.Never,
  endDate: input.endDate ? new Date(input.endDate) : null,
  endAfterCount: input.endAfterCount ?? null,
  timezone: input.timezone ?? null,
  nextAutoGenerateDate: input.nextAutoGenerateDate ? new Date(input.nextAutoGenerateDate) : null,
});

export const eventListSelect = {
  id: true,
  eventName: true,
  coverImage: true,
  programId: true,
  organizer: true,
  location: true,
  isPublished: true,
  isActive: true,
  isVerified: true,
  createdAt: true,
  updatedAt: true,
  program: { select: { id: true, name: true, imageUrl: true } },
  creator: {
    select: { id: true, firstName: true, lastName: true, username: true, profilePicture: true },
  },
} as const;

const publishedEventBaseWhere = {
  deletedAt: null,
  isActive: true,
  isPublished: true,
} as const;

const eventSessionForActivePickSelect = {
  eventId: true,
  id: true,
  status: true,
  registrationDate: true,
  deadline: true,
  cost: true,
  eventType: true,
  competitionLevel: true,
  isCurrentSession: true,
  session: {
    select: { id: true, sessionIdentifier: true, year: true, sessionNumber: true },
  },
} as const;

type EventSessionForActiveRow = Prisma.EventSessionGetPayload<{
  select: typeof eventSessionForActivePickSelect;
}>;

function buildHistorySummary(
  results: Array<{
    sessionId: string;
    placement: PlacementType;
    note: string | null;
    session: { year: string; sessionIdentifier: string } | null;
  }>,
  sessionId: string
): string | null {
  const r = results.find(x => x.sessionId === sessionId);
  if (!r) return null;
  const y = r.session?.year ?? r.session?.sessionIdentifier ?? '';
  const place = String(r.placement).replace(/_/g, ' ');
  const base = `History: ${y} ${place}`.replace(/\s+/g, ' ').trim();
  return r.note?.trim() ? `${base} (${r.note.trim()})` : base;
}

async function sessionsByEventIdMap(eventIds: string[]) {
  const map = new Map<string, EventSessionForActiveRow[]>();
  if (!eventIds.length) return map;
  const rows = await database.eventSession.findMany({
    where: { eventId: { in: eventIds } },
    select: eventSessionForActivePickSelect,
    orderBy: { deadline: 'asc' as const },
  });
  for (const r of rows) {
    const arr = map.get(r.eventId) ?? [];
    arr.push(r);
    map.set(r.eventId, arr);
  }
  return map;
}

async function attachActiveSessions<T extends { id: string }>(events: T[]) {
  const map = await sessionsByEventIdMap(events.map(e => e.id));
  return events.map(e => ({
    ...e,
    activeSession: pickActiveEventSession(map.get(e.id) ?? []),
  }));
}

const createEvent = async (creatorId: string, payload: ICreateEventPayload) => {
  const coverImage = payload.coverImage?.trim();
  if (!coverImage) {
    throw new Error('coverImage is required to create an event.');
  }
  const { repeatConfig, eventSessions, coverImage: _omitCover, ...eventFields } = payload;
  const repeatFrequency = repeatConfig?.frequency ?? RepeatFrequency.DontRepeat;

  return database.$transaction(async tx => {
    const event = await tx.event.create({
      data: {
        ...eventFields,
        coverImage,
        creatorId,
        repeatConfig: repeatConfig
          ? {
              create: repeatConfigFields(repeatConfig),
            }
          : undefined,
      },
      select: { id: true },
    });

    if (eventSessions?.length) {
      const explicitCurrentIdx = eventSessions.findIndex(es => es.isCurrentSession === true);
      const currentSessionIdx = explicitCurrentIdx >= 0 ? explicitCurrentIdx : 0;

      for (let i = 0; i < eventSessions.length; i++) {
        const s = eventSessions[i];
        let sessionId = s.sessionId;
        if (!sessionId && s.year) {
          const agg = await tx.session.aggregate({
            where: { year: s.year },
            _max: { sessionNumber: true },
          });
          const sessionNumber = s.sessionNumber ?? (agg._max.sessionNumber ?? 0) + 1;
          const bucketFormat = s.sessionBucketFormat ?? defaultSessionBucketFormat(repeatFrequency);
          const bucketDate = s.bucketDate ? new Date(s.bucketDate) : null;
          const baseIdentifier =
            s.sessionIdentifier?.trim() ||
            buildSessionIdentifier({
              year: s.year,
              format: bucketFormat,
              bucketQuarter: s.bucketQuarter,
              bucketMonth: s.bucketMonth,
              bucketDate,
            });
          let sessionIdentifier = baseIdentifier;
          for (let attempt = 0; attempt < 8; attempt++) {
            const clash = await tx.session.findUnique({
              where: { sessionIdentifier },
              select: { id: true },
            });
            if (!clash) break;
            sessionIdentifier = `${baseIdentifier}-${randomUUID().replace(/-/g, '').slice(0, 4)}`;
          }
          const createdSession = await tx.session.create({
            data: {
              sessionIdentifier,
              sessionNumber,
              year: s.year,
              bucketFormat,
            },
          });
          sessionId = createdSession.id;
        }

        await tx.eventSession.create({
          data: {
            eventId: event.id,
            sessionId: sessionId!,
            competitionLevel: s.competitionLevel,
            eventType: s.eventType,
            registrationDate: new Date(s.registrationDate),
            deadline: new Date(s.deadline),
            cost: toDecimal(s.cost),
            hasFinalDeadline: s.hasFinalDeadline ?? false,
            finalDeadline: s.finalDeadline ? new Date(s.finalDeadline) : null,
            lateFee: toDecimal(s.lateFee ?? 0),
            status: s.status ?? SessionStatus.Draft,
            isSharedToCommunity: s.isSharedToCommunity ?? false,
            isUserAgreementAccepted: s.isUserAgreementAccepted ?? false,
            autoGenerated: s.autoGenerated ?? false,
            isCurrentSession: i === currentSessionIdx,
            groups: buildEventGroupsNestedCreate(s.groups),
          },
        });
      }
    }

    const created = await tx.event.findFirst({
      where: { id: event.id },
      select: eventListSelect,
    });
    if (!created) {
      throw new Error('Failed to load event after create.');
    }
    return created;
  });
};

const getEventById = async (id: string) => {
  return database.event.findFirst({
    where: { id, deletedAt: null },
    include: {
      program: { select: { id: true, name: true, description: true, imageUrl: true } },
      repeatConfig: true,
      creator: {
        select: { id: true, firstName: true, lastName: true, username: true, profilePicture: true },
      },
      lastEditor: {
        select: { id: true, firstName: true, lastName: true, username: true },
      },
      verifiedBy: {
        select: { id: true, firstName: true, lastName: true, username: true },
      },
      eventSessions: {
        include: {
          session: { select: { id: true, sessionIdentifier: true, year: true, sessionNumber: true } },
          groups: { include: { rounds: true } },
        },
        orderBy: { deadline: 'asc' as const },
      },
      results: {
        include: {
          session: { select: { id: true, sessionIdentifier: true, year: true, sessionNumber: true } },
        },
        orderBy: { createdAt: 'desc' as const },
      },
      _count: { select: { applications: true, eventSessions: true } },
    },
  });
};

const getEventBare = async (id: string) => {
  return database.event.findFirst({
    where: { id, deletedAt: null },
    select: {
      id: true,
      eventName: true,
      creatorId: true,
      isVerified: true,
      isLocked: true,
      deletedAt: true,
      coverImage: true,
    },
  });
};

const getEvents = async (
  filters: IEventFilters,
  options: PaginationOptions
): Promise<PaginationResult<unknown>> => {
  const pagination = parsePaginationOptions(options);
  const { skip, take, orderBy } = createPaginationQuery(pagination);

  const where: Record<string, unknown> = {
    deletedAt: null,
  };

  if (filters.programId) {
    where.programId = filters.programId;
  }

  if (filters.location) {
    where.location = { contains: filters.location, mode: 'insensitive' };
  }

  if (filters.search) {
    where.OR = [
      { eventName: { contains: filters.search, mode: 'insensitive' } },
      { description: { contains: filters.search, mode: 'insensitive' } },
      { organizer: { contains: filters.search, mode: 'insensitive' } },
    ];
  }

  const sessionParts: Prisma.EventSessionWhereInput[] = [];
  if (filters.eventType) {
    sessionParts.push({ eventType: filters.eventType });
  }
  if (filters.groupCriteria) {
    sessionParts.push({
      groups: { some: { criteria: filters.groupCriteria } },
    });
  }
  if (filters.timeRangeFrom && filters.timeRangeTo) {
    const from = new Date(filters.timeRangeFrom);
    const to = new Date(filters.timeRangeTo);
    sessionParts.push({
      AND: [{ registrationDate: { lte: to } }, { deadline: { gte: from } }],
    });
  }
  if (filters.sessionScope) {
    sessionParts.push(sessionScopeWhereInput(filters.sessionScope));
  }
  const priceWhere = priceRangeOnSession(filters.priceMin, filters.priceMax);
  if (priceWhere) {
    sessionParts.push(priceWhere);
  }

  if (sessionParts.length > 0) {
    where.eventSessions = { some: { AND: sessionParts } };
  }

  const [data, total] = await Promise.all([
    database.event.findMany({
      where: where as any,
      select: eventListSelect,
      skip,
      take,
      orderBy,
    }),
    database.event.count({ where: where as any }),
  ]);

  const enriched = await attachActiveSessions(data);
  return createPaginationResult(enriched, total, pagination);
};

const getActiveEvents = async (
  options: PaginationOptions,
  price?: IFeedPriceFilters
): Promise<PaginationResult<unknown>> => {
  const pagination = parsePaginationOptions(options);
  const { skip, take, orderBy } = createPaginationQuery(pagination);
  const priceWhere = priceRangeOnSession(price?.priceMin, price?.priceMax);
  const where: Record<string, unknown> = {
    ...publishedEventBaseWhere,
    ...(priceWhere
      ? {
          eventSessions: {
            some: priceWhere,
          },
        }
      : {}),
  };

  const [data, total] = await Promise.all([
    database.event.findMany({
      where: where as any,
      select: eventListSelect,
      skip,
      take,
      orderBy,
    }),
    database.event.count({ where: where as any }),
  ]);

  const enriched = await attachActiveSessions(data);
  return createPaginationResult(enriched, total, pagination);
};

const getUpcomingEvents = async (
  options: PaginationOptions,
  price?: IFeedPriceFilters
): Promise<PaginationResult<unknown>> => {
  const pagination = parsePaginationOptions(options);
  const { skip, take, orderBy } = createPaginationQuery(pagination);
  const now = new Date();
  const priceWhere = priceRangeOnSession(price?.priceMin, price?.priceMax);
  const sessionAnd: Prisma.EventSessionWhereInput[] = [
    { deadline: { gte: now } },
    { status: { notIn: [SessionStatus.Completed, SessionStatus.Cancelled] } },
  ];
  if (priceWhere) sessionAnd.push(priceWhere);

  const where: Record<string, unknown> = {
    ...publishedEventBaseWhere,
    eventSessions: {
      some: { AND: sessionAnd },
    },
  };

  const [data, total] = await Promise.all([
    database.event.findMany({
      where: where as any,
      select: eventListSelect,
      skip,
      take,
      orderBy,
    }),
    database.event.count({ where: where as any }),
  ]);

  const enriched = await attachActiveSessions(data);
  return createPaginationResult(enriched, total, pagination);
};

const getFeedToday = async (
  options: PaginationOptions,
  price?: IFeedPriceFilters
): Promise<PaginationResult<unknown>> => {
  const pagination = parsePaginationOptions(options);
  const { skip, take, orderBy } = createPaginationQuery(pagination);
  const now = new Date();
  const startToday = startOfUtcDay(now);
  const endToday = endOfUtcDay(now);
  const priceWhere = priceRangeOnSession(price?.priceMin, price?.priceMax);
  const sessionAnd: Prisma.EventSessionWhereInput[] = [
    { registrationDate: { lte: endToday } },
    { deadline: { gte: startToday } },
    { status: { notIn: [SessionStatus.Cancelled] } },
  ];
  if (priceWhere) sessionAnd.push(priceWhere);

  const where = {
    ...publishedEventBaseWhere,
    eventSessions: { some: { AND: sessionAnd } },
  };

  const [data, total] = await Promise.all([
    database.event.findMany({
      where,
      select: eventListSelect,
      skip,
      take,
      orderBy,
    }),
    database.event.count({ where }),
  ]);

  const enriched = await attachActiveSessions(data);
  return createPaginationResult(enriched, total, pagination);
};

const getFeedHistory = async (
  options: PaginationOptions,
  price?: IFeedPriceFilters
): Promise<PaginationResult<unknown>> => {
  const pagination = parsePaginationOptions(options);
  const { skip, take, orderBy } = createPaginationQuery(pagination);
  const priceWhere = priceRangeOnSession(price?.priceMin, price?.priceMax);
  const sessionAnd: Prisma.EventSessionWhereInput[] = [sessionScopeWhereInput('history')];
  if (priceWhere) sessionAnd.push(priceWhere);

  const where = {
    ...publishedEventBaseWhere,
    eventSessions: { some: { AND: sessionAnd } },
  };

  const [data, total] = await Promise.all([
    database.event.findMany({
      where,
      select: eventListSelect,
      skip,
      take,
      orderBy,
    }),
    database.event.count({ where }),
  ]);

  const enriched = await attachActiveSessions(data);
  return createPaginationResult(enriched, total, pagination);
};

const getCalendarMonth = async (year: number, month: number, filters: ICalendarMonthFilters) => {
  const m0 = month - 1;
  const startMonth = new Date(Date.UTC(year, m0, 1, 0, 0, 0, 0));
  const lastDay = new Date(Date.UTC(year, m0 + 1, 0)).getUTCDate();
  const endMonth = endOfUtcDay(new Date(Date.UTC(year, m0, lastDay, 0, 0, 0, 0)));

  const priceWhere = priceRangeOnSession(filters.priceMin, filters.priceMax);
  const sessionAnd: Prisma.EventSessionWhereInput[] = [
    { registrationDate: { lte: endMonth } },
    { deadline: { gte: startMonth } },
  ];
  if (priceWhere) sessionAnd.push(priceWhere);

  const rows = await database.eventSession.findMany({
    where: {
      AND: sessionAnd,
      event: {
        ...publishedEventBaseWhere,
        ...(filters.programId ? { programId: filters.programId } : {}),
      },
    },
    select: {
      eventId: true,
      id: true,
      registrationDate: true,
      deadline: true,
    },
  });

  const pad = (n: number) => String(n).padStart(2, '0');
  const dayKey = (d: Date) =>
    `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())}`;

  const bumpMap = new Map<string, { sessionCount: number; eventIds: Set<string> }>();
  for (const row of rows) {
    let cursor = startOfUtcDay(
      row.registrationDate.getTime() < startMonth.getTime() ? startMonth : row.registrationDate
    );
    const lastSessionDay = startOfUtcDay(row.deadline);
    const limit =
      lastSessionDay.getTime() > endMonth.getTime() ? endMonth : lastSessionDay;
    while (cursor.getTime() <= limit.getTime()) {
      if (cursor.getTime() >= startMonth.getTime() && cursor.getTime() <= endMonth.getTime()) {
        const key = dayKey(cursor);
        const slot = bumpMap.get(key) ?? { sessionCount: 0, eventIds: new Set<string>() };
        slot.sessionCount += 1;
        slot.eventIds.add(row.eventId);
        bumpMap.set(key, slot);
      }
      cursor = addUtcDays(cursor, 1);
    }
  }

  const days: { date: string; sessionCount: number; eventCount: number }[] = [];
  for (let d = 1; d <= lastDay; d++) {
    const key = `${year}-${pad(month)}-${pad(d)}`;
    const slot = bumpMap.get(key);
    days.push({
      date: key,
      sessionCount: slot?.sessionCount ?? 0,
      eventCount: slot ? slot.eventIds.size : 0,
    });
  }

  return { year, month, days };
};

const getCalendarDayFeed = async (
  day: Date,
  filters: ICalendarDayFilters,
  options: PaginationOptions
): Promise<PaginationResult<unknown>> => {
  const pagination = parsePaginationOptions(options);
  const { skip, take, orderBy } = createPaginationQuery(pagination);
  const dayStart = startOfUtcDay(day);
  const dayEnd = endOfUtcDay(day);
  const priceWhere = priceRangeOnSession(filters.priceMin, filters.priceMax);
  const overlap: Prisma.EventSessionWhereInput = {
    AND: [{ registrationDate: { lte: dayEnd } }, { deadline: { gte: dayStart } }],
  };
  const sessionSome: Prisma.EventSessionWhereInput[] = [overlap];
  if (priceWhere) sessionSome.push(priceWhere);

  const eventWhere = {
    ...publishedEventBaseWhere,
    ...(filters.programId ? { programId: filters.programId } : {}),
    eventSessions: { some: { AND: sessionSome } },
  };

  const [events, total] = await Promise.all([
    database.event.findMany({
      where: eventWhere,
      select: eventListSelect,
      skip,
      take,
      orderBy,
    }),
    database.event.count({ where: eventWhere }),
  ]);

  const ids = events.map(e => e.id);
  const sessionsOnDay = await database.eventSession.findMany({
    where: {
      eventId: { in: ids },
      AND: sessionSome,
    },
    include: {
      session: { select: { id: true, sessionIdentifier: true, year: true, sessionNumber: true } },
    },
    orderBy: { registrationDate: 'asc' as const },
  });

  const results = await database.eventResult.findMany({
    where: { eventId: { in: ids } },
    include: {
      session: { select: { id: true, year: true, sessionIdentifier: true } },
    },
    orderBy: { createdAt: 'desc' as const },
  });

  const byEvent = new Map<string, typeof sessionsOnDay>();
  for (const s of sessionsOnDay) {
    const arr = byEvent.get(s.eventId) ?? [];
    arr.push(s);
    byEvent.set(s.eventId, arr);
  }

  const allSessions = await sessionsByEventIdMap(ids);

  const data = events.map(ev => {
    const daySessions = byEvent.get(ev.id) ?? [];
    const withHistory = daySessions.map(s => ({
      ...s,
      historySummary: buildHistorySummary(results, s.sessionId),
    }));
    return {
      ...ev,
      sessionsOnDay: withHistory,
      activeSession: pickActiveEventSession(allSessions.get(ev.id) ?? []),
    };
  });

  return createPaginationResult(data, total, pagination);
};

const updateEventById = async (id: string, data: Record<string, unknown>) => {
  return database.event.update({
    where: { id },
    data: data as any,
    select: eventListSelect,
  });
};

const updateCurrentEventSessionForEvent = async (
  eventId: string,
  patch: IUpdateCurrentEventSessionPayload
) => {
  const current = await database.eventSession.findFirst({
    where: { eventId, isCurrentSession: true },
    select: { id: true },
  });
  if (!current) {
    return null;
  }

  const data: Prisma.EventSessionUpdateInput = {};
  if (patch.competitionLevel !== undefined) {
    data.competitionLevel = patch.competitionLevel;
  }
  if (patch.eventType !== undefined) {
    data.eventType = patch.eventType;
  }
  if (patch.registrationDate !== undefined) {
    data.registrationDate = new Date(patch.registrationDate);
  }
  if (patch.deadline !== undefined) {
    data.deadline = new Date(patch.deadline);
  }
  if (patch.cost !== undefined) {
    data.cost = toDecimal(patch.cost);
  }
  if (patch.hasFinalDeadline !== undefined) {
    data.hasFinalDeadline = patch.hasFinalDeadline;
  }
  if (patch.finalDeadline !== undefined) {
    data.finalDeadline = patch.finalDeadline ? new Date(patch.finalDeadline) : null;
  }
  if (patch.lateFee !== undefined) {
    data.lateFee = toDecimal(patch.lateFee);
  }
  if (patch.status !== undefined) {
    data.status = patch.status;
  }
  if (patch.isSharedToCommunity !== undefined) {
    data.isSharedToCommunity = patch.isSharedToCommunity;
  }
  if (patch.isUserAgreementAccepted !== undefined) {
    data.isUserAgreementAccepted = patch.isUserAgreementAccepted;
  }
  if (patch.autoGenerated !== undefined) {
    data.autoGenerated = patch.autoGenerated;
  }

  if (Object.keys(data).length === 0) {
    return null;
  }

  return database.eventSession.update({
    where: { id: current.id },
    data,
    include: {
      session: { select: { id: true, sessionIdentifier: true, year: true, sessionNumber: true } },
      groups: { include: { rounds: true } },
    },
  });
};

const upsertRepeatConfig = async (eventId: string, input: IRepeatConfigInput) => {
  const fields = repeatConfigFields(input);
  return database.repeatConfig.upsert({
    where: { eventId },
    create: { eventId, ...fields },
    update: fields,
  });
};

const deleteRepeatConfigByEventId = async (eventId: string) => {
  return database.repeatConfig.deleteMany({ where: { eventId } });
};

const softDeleteEvent = async (id: string) => {
  return database.event.update({
    where: { id },
    data: { deletedAt: new Date(), isActive: false },
    select: { id: true, deletedAt: true },
  });
};

const listEventSessions = async (eventId: string) => {
  return database.eventSession.findMany({
    where: { eventId },
    include: {
      session: true,
      groups: { include: { rounds: true } },
    },
    orderBy: { createdAt: 'asc' },
  });
};

const verifyEvent = async (eventId: string, userId: string) => {
  return database.event.update({
    where: { id: eventId },
    data: {
      isVerified: true,
      verifiedById: userId,
      verifiedAt: new Date(),
      version: { increment: 1 },
    },
    select: eventListSelect,
  });
};

const reapplyApplication = async (eventId: string, userId: string, note?: string | null) => {
  return database.eventApplication.update({
    where: { eventId_userId: { eventId, userId } },
    data: {
      status: EventApplicationStatus.Pending,
      ...(note !== undefined ? { note } : {}),
    },
    include: {
      user: {
        select: { id: true, firstName: true, lastName: true, username: true, profilePicture: true },
      },
    },
  });
};

const createApplication = async (eventId: string, userId: string, note?: string | null) => {
  return database.eventApplication.create({
    data: {
      eventId,
      userId,
      note: note ?? null,
    },
    include: {
      user: {
        select: { id: true, firstName: true, lastName: true, username: true, profilePicture: true },
      },
    },
  });
};

const findApplication = async (eventId: string, userId: string) => {
  return database.eventApplication.findUnique({
    where: { eventId_userId: { eventId, userId } },
  });
};

const withdrawApplication = async (eventId: string, userId: string) => {
  return database.eventApplication.update({
    where: { eventId_userId: { eventId, userId } },
    data: { status: EventApplicationStatus.Withdrawn },
  });
};

const listApplicationsForEvent = async (eventId: string) => {
  return database.eventApplication.findMany({
    where: { eventId, status: { not: EventApplicationStatus.Withdrawn } },
    include: {
      user: {
        select: { id: true, firstName: true, lastName: true, username: true, email: true, profilePicture: true },
      },
    },
    orderBy: { createdAt: 'desc' },
  });
};

const programExists = async (programId: string) => {
  return database.program.findFirst({
    where: { id: programId, isDeleted: false },
    select: { id: true },
  });
};

const sessionsExist = async (sessionIds: string[]) => {
  const unique = [...new Set(sessionIds)];
  const rows = await database.session.findMany({
    where: { id: { in: unique } },
    select: { id: true },
  });
  return rows.length === unique.length;
};

export const EventRepository = {
  createEvent,
  getEventById,
  getEventBare,
  getEvents,
  getActiveEvents,
  getUpcomingEvents,
  getFeedToday,
  getFeedHistory,
  getCalendarMonth,
  getCalendarDayFeed,
  updateEventById,
  updateCurrentEventSessionForEvent,
  upsertRepeatConfig,
  deleteRepeatConfigByEventId,
  softDeleteEvent,
  listEventSessions,
  verifyEvent,
  createApplication,
  reapplyApplication,
  findApplication,
  withdrawApplication,
  listApplicationsForEvent,
  programExists,
  sessionsExist,
};
