import { PaginationOptions } from '../../interfaces';
import {
  CompetitionLevel,
  EventType,
  GroupCriteria,
  MonthWeek,
  RepeatEndType,
  RepeatFrequency,
  RepeatUnit,
  RoundCondition,
  SessionBucketFormat,
  SessionStatus,
  WeekDay,
} from '../../../prisma/generated/enums';

/** Contribution points for wiki-style participation */
export const EVENT_CONTRIBUTION_SCORE = {
  CREATE: 10,
  UPDATE: 5,
  VERIFY: 15,
  APPLY: 3,
} as const;

/** Matches Prisma model `RepeatConfig` */
export interface IRepeatConfigInput {
  frequency?: RepeatFrequency;
  startDate?: Date | string;
  interval?: number;
  unit?: RepeatUnit | null;
  weekDays?: WeekDay[];
  monthDay?: number | null;
  monthWeek?: MonthWeek | null;
  monthWeekDay?: WeekDay | null;
  endType?: RepeatEndType;
}

/** Matches Prisma model `EventRound` */
export interface IEventRoundInput {
  roundType: CompetitionLevel;
  deadline: Date | string;
  cost: string | number;
  hasFinalDeadline?: boolean;
  finalDeadline?: Date | string | null;
  lateFee?: string | number;
  description?: string | null;
}

/** Matches Prisma model `EventGroup` (+ nested `rounds` → `EventRound`) */
export interface IEventGroupInput {
  name: string;
  criteria: GroupCriteria;
  condition: RoundCondition;
  value: number;
  rounds?: IEventRoundInput[];
}

/**
 * Matches Prisma model `EventSession` (+ optional nested `EventGroup` / `EventRound`).
 * Provide either `sessionId` (existing `Session`) OR `year` + `competitionLevel` to create a new `Session`.
 */
export interface IEventSessionInput {
  /** Existing `Session.id` */
  sessionId?: string;
  /** When creating `Session`: calendar year label, e.g. "2026" */
  year?: string;
  /**
   * When creating `Session`: optional final key; if omitted, backend builds from `year` +
   * `sessionBucketFormat` (or repeat frequency default) + bucket hints, e.g. `2026-Q1`, `2026-JAN`.
   */
  sessionIdentifier?: string | null;
  /**
   * Pattern for auto `sessionIdentifier`. If omitted, derived from event `repeatConfig.frequency`
   * (e.g. Quarterly → `Year_Q`, Monthly → `Year_MMM`).
   */
  sessionBucketFormat?: SessionBucketFormat | null;
  /** For `Year_Q`: 1–4; if omitted, derived from `bucketDate` or defaults within `year`. */
  bucketQuarter?: number | null;
  /** For `Year_MMM` / `Year_MM`: 1–12. */
  bucketMonth?: number | null;
  /** Anchor date for quarter / week / day formats when not using explicit month/quarter. */
  bucketDate?: Date | string | null;
  /** When creating `Session`: maps to `Session.sessionNumber` (default = max for year + 1) */
  sessionNumber?: number;
  /** Matches `EventSession.competitionLevel` (Prisma name; not "sessionLevel") */
  competitionLevel: CompetitionLevel;
  eventType: EventType;
  registrationDate: Date | string;
  deadline: Date | string;
  cost: string | number;
  hasFinalDeadline?: boolean;
  finalDeadline?: Date | string | null;
  lateFee?: string | number;
  status?: SessionStatus;
  isSharedToCommunity?: boolean;
  isUserAgreementAccepted?: boolean;
  autoGenerated?: boolean;
  /** Mark the primary session for detail UI; at most one per create payload (default: first session). */
  isCurrentSession?: boolean;
  groups?: IEventGroupInput[];
}

/** Matches Prisma model `Event` (+ nested config) */
export interface ICreateEventPayload {
  eventName: string;
  coverImage?: string;
  programId: string;
  organizer: string;
  location?: string | null;
  eventPortal: string;
  registrationPortal: string;
  description: string;
  note?: string | null;
  isPublished?: boolean;
  repeatConfig?: IRepeatConfigInput | null;
  eventSessions?: IEventSessionInput[];
}

/** Partial update for the row where `EventSession.isCurrentSession` is true. */
export interface IUpdateCurrentEventSessionPayload {
  competitionLevel?: CompetitionLevel;
  eventType?: EventType;
  registrationDate?: Date | string;
  deadline?: Date | string;
  cost?: string | number;
  hasFinalDeadline?: boolean;
  finalDeadline?: Date | string | null;
  lateFee?: string | number;
  status?: SessionStatus;
  isSharedToCommunity?: boolean;
  isUserAgreementAccepted?: boolean;
  autoGenerated?: boolean;
}

export interface IUpdateEventPayload {
  eventName?: string;
  coverImage?: string;
  programId?: string;
  organizer?: string;
  location?: string | null;
  eventPortal?: string;
  registrationPortal?: string;
  description?: string;
  note?: string | null;
  isPublished?: boolean;
  isActive?: boolean;
  isLocked?: boolean;
  repeatConfig?: IRepeatConfigInput | null;
  /** Patch the primary session (`isCurrentSession`) for this event. */
  currentEventSession?: IUpdateCurrentEventSessionPayload;
}

export type EventSessionScopeFilter = 'today' | 'upcoming' | 'history';

export interface IEventFilters {
  search?: string;
  programId?: string;
  eventType?: EventType;
  location?: string;
  groupCriteria?: GroupCriteria;
  timeRangeFrom?: string;
  timeRangeTo?: string;
  /** Filter events that have at least one session in this bucket (UTC); combine with priceMin/priceMax on sessions. */
  sessionScope?: EventSessionScopeFilter;
  priceMin?: string;
  priceMax?: string;
}

/** Optional price filter on session `cost` for curated feeds. */
export interface IFeedPriceFilters {
  priceMin?: string;
  priceMax?: string;
}

export interface IEventQuery {
  filters: IEventFilters;
  options: PaginationOptions;
}
