import { Prisma } from '../../../prisma/generated/client';
import {
  RepeatFrequency,
  SessionBucketType,
  SessionCreationMode,
  SessionStatus,
} from '../../../prisma/generated/enums';
import { database } from '../../config/database';
import {
  createPaginationQuery,
  createPaginationResult,
  PaginationOptions,
  PaginationResult,
  parsePaginationOptions,
} from '../../utils/paginate';
import {
  ICreateEventPayload,
  IEventFilters,
  IFeedPriceFilters,
  IRepeatConfigInput,
  IUpdateCurrentEventSessionPayload,
} from './event.interface';
import {
  endOfUtcDay,
  priceRangeOnSession,
  sessionScopeWhereInput,
  startOfUtcDay,
  withEventSessionCostEstimation,
} from './event.helpers';
import {
  attachActiveSessions,
  eventGroupsToNestedCreate,
  eventListSelect,
  extractEventNameParts,
  frequencySuffix,
  publishedEventBaseWhere,
  repeatConfigFields,
  resolveRepeatFrequency,
  sessionTypeFromRepeatFrequency,
  toDecimal,
} from './event.utils';
const eventAuditSnapshotSelect = {
  version: true,
  programId: true,
  organizer: true,
  location: true,
  eventPortal: true,
  registrationPortal: true,
  description: true,
  note: true,
  isPublished: true,
  isActive: true,
  coverImage: true,
  repeatConfig: true,
  eventSession: {
    select: {
      id: true,
      competitionLevel: true,
      eventType: true,
      registrationDate: true,
      deadline: true,
      cost: true,
      status: true,
      hasFinalDeadline: true,
      finalDeadline: true,
      lateFee: true,
      isSharedToCommunity: true,
      isUserAgreementAccepted: true,
      autoGenerated: true,
    },
  },
} as const;

// POST /events
const createEvent = async (creatorId: string, payload: ICreateEventPayload) => {
  const coverImage = payload.coverImage?.trim();
  if (!coverImage) {
    throw new Error('coverImage is required to create an event.');
  }
  const { repeatConfig, eventSession, coverImage: _omitCover, ...eventFields } = payload;
  const repeatFrequency = resolveRepeatFrequency(repeatConfig);
  const firstEventSession = payload.eventSession;
  const anchorDate = firstEventSession?.registrationDate
    ? new Date(firstEventSession.registrationDate)
    : repeatConfig?.startDate
      ? new Date(repeatConfig.startDate)
      : new Date();
  const manualSessionType = firstEventSession?.session ?? null;
  const manualSessionValue = firstEventSession?.sessionValue?.trim() || '';
  const manualLevel = firstEventSession?.sessionLevel?.trim() || '';
  const autoValue = frequencySuffix(repeatFrequency, anchorDate);
  const yearForEvent =
    repeatFrequency === RepeatFrequency.DontRepeat
      ? (firstEventSession?.year?.trim() || String(anchorDate.getUTCFullYear()))
      : String(anchorDate.getUTCFullYear());
  const sessionTypeForEvent: SessionBucketType =
    repeatFrequency === RepeatFrequency.DontRepeat
      ? (manualSessionType ?? SessionBucketType.Custom)
      : sessionTypeFromRepeatFrequency(repeatFrequency);
  const isYearlySession = sessionTypeForEvent === SessionBucketType.Yearly;
  const sessionValueForEvent =
    repeatFrequency === RepeatFrequency.DontRepeat ? manualSessionValue || autoValue : autoValue;
  const suffixForEvent = (() => {
    if (repeatFrequency === RepeatFrequency.DontRepeat) {
      if (manualLevel && manualLevel.startsWith(`${yearForEvent}-`)) {
        return manualLevel.slice(yearForEvent.length + 1);
      }
      if (manualLevel) return manualLevel;
      return sessionValueForEvent;
    }
    // Repeating events: the bucket label is always derived from the chosen repeat frequency + anchor date.
    return sessionValueForEvent;
  })();
  const sessionLevelForEvent = isYearlySession ? `${yearForEvent}` : `${yearForEvent}-${suffixForEvent}`;
  const eventNameWithSuffix = isYearlySession
    ? `${payload.eventName.trim()}-${yearForEvent}`
    : `${payload.eventName.trim()}-${yearForEvent}-${suffixForEvent}`;
  const eventNameParts = extractEventNameParts(eventNameWithSuffix, payload.eventName);

  return database.$transaction(async tx => {
    const event = await tx.event.create({
      data: {
        ...eventFields,
        eventName: eventNameWithSuffix,
        baseEventName: payload.eventName.trim(),
        eventYear: eventNameParts.eventYear,
        eventSessionLabel: eventNameParts.eventSessionLabel,
        coverImage,
        creatorId,
        repeatConfig: repeatConfig
          ? {
            create: repeatConfigFields(repeatConfig),
          }
          : undefined,
      },
      select: { id: true },
    });

    if (eventSession) {
      const s = {
        ...eventSession,
        year: yearForEvent,
        sessionLevel: sessionLevelForEvent,
        session: sessionTypeForEvent,
        sessionValue: sessionValueForEvent,
      };
      const sessionCreationMode: SessionCreationMode =
        s.sessionId || repeatFrequency === RepeatFrequency.DontRepeat
          ? SessionCreationMode.Manual
          : SessionCreationMode.Auto;
      let sessionId = s.sessionId;
      if (!sessionId && s.year) {
        const sessionLevelValue = (() => {
          return s.sessionLevel?.trim() || `${s.year}-${s.sessionValue}`;
        })();
        const existingSession = await tx.session.findUnique({
          where: { sessionLevel: sessionLevelValue },
          select: { id: true },
        });
        if (existingSession) {
          sessionId = existingSession.id;
        } else {
          const createdSession = await tx.session.create({
            data: {
              session: s.session ?? SessionBucketType.Custom,
              sessionValue: s.sessionValue ?? autoValue,
              sessionLevel: sessionLevelValue,
              year: s.year,
              creationMode: sessionCreationMode,
            },
          });
          sessionId = createdSession.id;
        }
      }

      await tx.eventSession.create({
        data: {
          eventId: event.id,
          sessionId: sessionId!,
          competitionLevel: s.competitionLevel,
          eventType: s.eventType,
          registrationDate: new Date(s.registrationDate),
          deadline: new Date(s.deadline),
          cost: toDecimal(s.cost),
          hasFinalDeadline: s.hasFinalDeadline ?? false,
          finalDeadline: s.finalDeadline ? new Date(s.finalDeadline) : null,
          lateFee: toDecimal(s.lateFee ?? 0),
          status: s.status ?? SessionStatus.Unverified,
          isSharedToCommunity: s.isSharedToCommunity ?? false,
          isUserAgreementAccepted: s.isUserAgreementAccepted ?? false,
          autoGenerated: sessionCreationMode === SessionCreationMode.Auto,
          isCurrentSession: true,
          groups: eventGroupsToNestedCreate(s.groups),
        },
      });
    }

    const created = await tx.event.findFirst({
      where: { id: event.id },
      select: eventListSelect,
    });
    if (!created) {
      throw new Error('Failed to load event after create.');
    }
    return created;
  });
};

// GET /events/:eventId
const getEventById = async (id: string) => {
  const event = await database.event.findFirst({
    where: { id, deletedAt: null },
    select: {
      id: true,
      eventName: true,
      coverImage: true,
      programId: true,
      organizer: true,
      location: true,
      eventPortal: true,
      registrationPortal: true,
      description: true,
      note: true,
      isPublished: true,
      isActive: true,
      program: { select: { id: true, name: true, description: true, imageUrl: true } },
      repeatConfig: {
        select: {
          id: true,
          frequency: true,
          startDate: true,
          nextAutoGenerateDate: true,
        },
      },
      creator: {
        select: { id: true, firstName: true, lastName: true, username: true, profilePicture: true },
      },
      lastEditor: {
        select: { id: true, firstName: true, lastName: true, username: true },
      },
      eventSession: {
        select: {
          id: true,
          competitionLevel: true,
          eventType: true,
          registrationDate: true,
          deadline: true,
          cost: true,
          hasFinalDeadline: true,
          finalDeadline: true,
          lateFee: true,
          status: true,
          isCurrentSession: true,
          session: {
            select: {
              id: true,
              session: true,
              sessionValue: true,
              sessionLevel: true,
              year: true,
              creationMode: true,
            },
          },
          groups: {
            select: {
              id: true,
              name: true,
              criteria: true,
              condition: true,
              value: true,
              rounds: {
                select: {
                  id: true,
                  roundType: true,
                  deadline: true,
                  cost: true,
                  hasFinalDeadline: true,
                  finalDeadline: true,
                  lateFee: true,
                  description: true,
                },
              },
            },
          },
        },
      },
      results: {
        include: {
          session: {
            select: {
              id: true,
              session: true,
              sessionValue: true,
              sessionLevel: true,
              year: true,
              creationMode: true,
            },
          },
        },
        orderBy: { createdAt: 'desc' as const },
      },
      _count: { select: { applications: true } },
    },
  });
  if (!event) return null;
  return {
    ...event,
    eventSession: event.eventSession ? withEventSessionCostEstimation(event.eventSession) : null,
  };
};

// Internal: minimal event row for auth / guard checks (used by multiple service methods).
const getEventBare = async (id: string) => {
  return database.event.findFirst({
    where: { id, deletedAt: null },
    select: {
      id: true,
      eventName: true,
      creatorId: true,
      deletedAt: true,
      coverImage: true,
      version: true,
    },
  });
};


// Internal: snapshot for EditLog diffing on PATCH /events/:eventId (before/after comparison).
const getEventAuditSnapshot = async (id: string) => {
  return database.event.findFirst({
    where: { id, deletedAt: null },
    select: eventAuditSnapshotSelect,
  });
};

export type EventAuditSnapshot = NonNullable<Awaited<ReturnType<typeof getEventAuditSnapshot>>>;

// Internal: persists edit history rows (written from EventService.updateEvent when changes are detected).
const createEditLog = async (input: {
  eventId: string;
  version: number;
  editorId: string;
  changedFields: string[];
  previousValues: Prisma.InputJsonValue;
}) => {
  return database.editLog.create({
    data: {
      eventId: input.eventId,
      version: input.version,
      editorId: input.editorId,
      changedFields: input.changedFields,
      previousValues: input.previousValues,
    },
    select: { id: true, version: true, createdAt: true },
  });
};

// GET /events
const getEvents = async (
  filters: IEventFilters,
  options: PaginationOptions
): Promise<PaginationResult<unknown>> => {
  const pagination = parsePaginationOptions(options);
  const { skip, take, orderBy } = createPaginationQuery(pagination);

  const where: Record<string, unknown> = {
    deletedAt: null,
  };

  if (filters.programId) {
    where.programId = filters.programId;
  }

  if (filters.location) {
    where.location = { contains: filters.location, mode: 'insensitive' };
  }

  if (filters.search) {
    where.OR = [
      { eventName: { contains: filters.search, mode: 'insensitive' } },
      { description: { contains: filters.search, mode: 'insensitive' } },
      { organizer: { contains: filters.search, mode: 'insensitive' } },
    ];
  }

  const sessionParts: Prisma.EventSessionWhereInput[] = [];
  if (filters.eventType) {
    sessionParts.push({ eventType: filters.eventType });
  }
  if (filters.groupCriteria) {
    sessionParts.push({
      groups: { some: { criteria: filters.groupCriteria } },
    });
  }
  if (filters.timeRangeFrom && filters.timeRangeTo) {
    const from = new Date(filters.timeRangeFrom);
    const to = new Date(filters.timeRangeTo);
    sessionParts.push({
      AND: [{ registrationDate: { lte: to } }, { deadline: { gte: from } }],
    });
  }
  if (filters.sessionScope) {
    sessionParts.push(sessionScopeWhereInput(filters.sessionScope));
  }
  const priceWhere = priceRangeOnSession(filters.priceMin, filters.priceMax);
  if (priceWhere) {
    sessionParts.push(priceWhere);
  }

  if (sessionParts.length > 0) {
    where.eventSession = { is: { AND: sessionParts } };
  }

  const [data, total] = await Promise.all([
    database.event.findMany({
      where: where as any,
      select: eventListSelect,
      skip,
      take,
      orderBy,
    }),
    database.event.count({ where: where as any }),
  ]);

  const enriched = await attachActiveSessions(data);
  return createPaginationResult(enriched, total, pagination);
};

// GET /events/feed/active
const getActiveEvents = async (
  options: PaginationOptions,
  price?: IFeedPriceFilters
): Promise<PaginationResult<unknown>> => {
  const pagination = parsePaginationOptions(options);
  const { skip, take, orderBy } = createPaginationQuery(pagination);
  const priceWhere = priceRangeOnSession(price?.priceMin, price?.priceMax);
  const where: Record<string, unknown> = {
    ...publishedEventBaseWhere,
    ...(priceWhere
      ? {
        eventSession: {
          is: priceWhere,
        },
      }
      : {}),
  };

  const [data, total] = await Promise.all([
    database.event.findMany({
      where: where as any,
      select: eventListSelect,
      skip,
      take,
      orderBy,
    }),
    database.event.count({ where: where as any }),
  ]);

  const enriched = await attachActiveSessions(data);
  return createPaginationResult(enriched, total, pagination);
};

// GET /events/feed/upcoming
const getUpcomingEvents = async (
  options: PaginationOptions,
  price?: IFeedPriceFilters
): Promise<PaginationResult<unknown>> => {
  const pagination = parsePaginationOptions(options);
  const { skip, take, orderBy } = createPaginationQuery(pagination);
  const now = new Date();
  const priceWhere = priceRangeOnSession(price?.priceMin, price?.priceMax);
  const sessionAnd: Prisma.EventSessionWhereInput[] = [
    { deadline: { gte: now } },
    { status: { notIn: [SessionStatus.Completed, SessionStatus.Cancelled] } },
  ];
  if (priceWhere) sessionAnd.push(priceWhere);

  const where: Record<string, unknown> = {
    ...publishedEventBaseWhere,
    eventSession: {
      is: { AND: sessionAnd },
    },
  };

  const [data, total] = await Promise.all([
    database.event.findMany({
      where: where as any,
      select: eventListSelect,
      skip,
      take,
      orderBy,
    }),
    database.event.count({ where: where as any }),
  ]);

  const enriched = await attachActiveSessions(data);
  return createPaginationResult(enriched, total, pagination);
};

// GET /events/feed/today
const getFeedToday = async (
  options: PaginationOptions,
  price?: IFeedPriceFilters
): Promise<PaginationResult<unknown>> => {
  const pagination = parsePaginationOptions(options);
  const { skip, take, orderBy } = createPaginationQuery(pagination);
  const now = new Date();
  const startToday = startOfUtcDay(now);
  const endToday = endOfUtcDay(now);
  const priceWhere = priceRangeOnSession(price?.priceMin, price?.priceMax);
  const sessionAnd: Prisma.EventSessionWhereInput[] = [
    { registrationDate: { lte: endToday } },
    { deadline: { gte: startToday } },
    { status: { notIn: [SessionStatus.Cancelled] } },
  ];
  if (priceWhere) sessionAnd.push(priceWhere);

  const where = {
    ...publishedEventBaseWhere,
    eventSession: { is: { AND: sessionAnd } },
  };

  const [data, total] = await Promise.all([
    database.event.findMany({
      where,
      select: eventListSelect,
      skip,
      take,
      orderBy,
    }),
    database.event.count({ where }),
  ]);

  const enriched = await attachActiveSessions(data);
  return createPaginationResult(enriched, total, pagination);
};

// GET /events/feed/history
const getFeedHistory = async (
  options: PaginationOptions,
  price?: IFeedPriceFilters
): Promise<PaginationResult<unknown>> => {
  const pagination = parsePaginationOptions(options);
  const { skip, take, orderBy } = createPaginationQuery(pagination);
  const priceWhere = priceRangeOnSession(price?.priceMin, price?.priceMax);
  const sessionAnd: Prisma.EventSessionWhereInput[] = [sessionScopeWhereInput('history')];
  if (priceWhere) sessionAnd.push(priceWhere);

  const where = {
    ...publishedEventBaseWhere,
    eventSession: { is: { AND: sessionAnd } },
  };

  const [data, total] = await Promise.all([
    database.event.findMany({
      where,
      select: eventListSelect,
      skip,
      take,
      orderBy,
    }),
    database.event.count({ where }),
  ]);

  const enriched = await attachActiveSessions(data);
  return createPaginationResult(enriched, total, pagination);
};

// PATCH /events/:eventId (updates the `events` row; service may also update related tables)
const updateEventById = async (id: string, data: Record<string, unknown>) => {
  return database.event.update({
    where: { id },
    data: data as any,
    select: eventListSelect,
  });
};

// PATCH /events/:eventId (body.currentEventSession) — updates the single `event_sessions` row for this event.
const updateCurrentEventSessionForEvent = async (
  eventId: string,
  patch: IUpdateCurrentEventSessionPayload
) => {
  const current = await database.eventSession.findFirst({
    where: { eventId },
    select: { id: true },
  });
  if (!current) {
    return null;
  }

  const data: Prisma.EventSessionUpdateInput = {};
  if (patch.competitionLevel !== undefined) {
    data.competitionLevel = patch.competitionLevel;
  }
  if (patch.eventType !== undefined) {
    data.eventType = patch.eventType;
  }
  if (patch.registrationDate !== undefined) {
    data.registrationDate = new Date(patch.registrationDate);
  }
  if (patch.deadline !== undefined) {
    data.deadline = new Date(patch.deadline);
  }
  if (patch.cost !== undefined) {
    data.cost = toDecimal(patch.cost);
  }
  if (patch.hasFinalDeadline !== undefined) {
    data.hasFinalDeadline = patch.hasFinalDeadline;
  }
  if (patch.finalDeadline !== undefined) {
    data.finalDeadline = patch.finalDeadline ? new Date(patch.finalDeadline) : null;
  }
  if (patch.lateFee !== undefined) {
    data.lateFee = toDecimal(patch.lateFee);
  }
  if (patch.status !== undefined) {
    data.status = patch.status;
  }
  if (patch.isSharedToCommunity !== undefined) {
    data.isSharedToCommunity = patch.isSharedToCommunity;
  }
  if (patch.isUserAgreementAccepted !== undefined) {
    data.isUserAgreementAccepted = patch.isUserAgreementAccepted;
  }
  if (patch.autoGenerated !== undefined) {
    data.autoGenerated = patch.autoGenerated;
  }

  if (Object.keys(data).length === 0) {
    return null;
  }

  const updated = await database.eventSession.update({
    where: { id: current.id },
    data,
    include: {
      session: {
        select: {
          id: true,
          session: true,
          sessionValue: true,
          sessionLevel: true,
          year: true,
          creationMode: true,
        },
      },
      groups: { include: { rounds: true } },
    },
  });
  return withEventSessionCostEstimation(updated);
};

// PATCH /events/:eventId (body.repeatConfig) — upserts `repeat_configs` for this event.
const upsertRepeatConfig = async (eventId: string, input: IRepeatConfigInput) => {
  const fields = repeatConfigFields(input);
  return database.repeatConfig.upsert({
    where: { eventId },
    create: { eventId, ...fields },
    update: fields,
  });
};

// PATCH /events/:eventId (body.repeatConfig=null) — deletes `repeat_configs` for this event.
const deleteRepeatConfigByEventId = async (eventId: string) => {
  return database.repeatConfig.deleteMany({ where: { eventId } });
};

// DELETE /events/:eventId
const softDeleteEvent = async (id: string) => {
  return database.event.update({
    where: { id },
    data: { deletedAt: new Date(), isActive: false },
    select: { id: true, deletedAt: true },
  });
};

// POST /events/:eventId/verify — publishes the event’s single `event_sessions` row when it is Unverified.
const verifyCurrentSessionForEvent = async (eventId: string) => {
  const current = await database.eventSession.findFirst({
    where: { eventId },
    include: {
      session: {
        select: {
          id: true,
          session: true,
          sessionValue: true,
          sessionLevel: true,
          year: true,
          creationMode: true,
        },
      },
      groups: { include: { rounds: true } },
    },
  });
  if (!current) {
    return null;
  }
  if (current.status !== SessionStatus.Unverified) {
    return withEventSessionCostEstimation(current);
  }
  const updated = await database.eventSession.update({
    where: { id: current.id },
    data: { status: SessionStatus.Published },
    include: {
      session: {
        select: {
          id: true,
          session: true,
          sessionValue: true,
          sessionLevel: true,
          year: true,
          creationMode: true,
        },
      },
      groups: { include: { rounds: true } },
    },
  });
  return withEventSessionCostEstimation(updated);
};

// Internal: validation helper for POST /events (programId must exist).
const programExists = async (programId: string) => {
  return database.program.findFirst({
    where: { id: programId, isDeleted: false },
    select: { id: true },
  });
};

// Internal: validation helper for POST /events when linking an existing `sessions` row via eventSession.sessionId.
const sessionsExist = async (sessionIds: string[]) => {
  const unique = [...new Set(sessionIds)];
  const rows = await database.session.findMany({
    where: { id: { in: unique } },
    select: { id: true },
  });
  return rows.length === unique.length;
};

export const EventRepository = {
  createEvent,
  getEventById,
  getEventBare,
  getEventAuditSnapshot,
  createEditLog,
  getEvents,
  getActiveEvents,
  getUpcomingEvents,
  getFeedToday,
  getFeedHistory,
  updateEventById,
  updateCurrentEventSessionForEvent,
  upsertRepeatConfig,
  deleteRepeatConfigByEventId,
  softDeleteEvent,
  verifyCurrentSessionForEvent,
  programExists,
  sessionsExist,
};
