import { z } from 'zod';
import {
  CompetitionLevel,
  EventType,
  GroupCriteria,
  MonthWeek,
  RepeatEndType,
  RepeatFrequency,
  RepeatUnit,
  RoundCondition,
  SessionBucketFormat,
  SessionStatus,
  WeekDay,
} from '../../../prisma/generated/enums';

const eventIdParam = z.object({
  eventId: z.string().min(1, 'eventId is required'),
});

const mergeEventFormDataField = (raw: unknown) => {
  if (typeof raw !== 'object' || raw === null) return raw;
  const b = raw as Record<string, unknown>;
  if (typeof b.data === 'string' && b.data.trim()) {
    try {
      const parsed = JSON.parse(b.data) as Record<string, unknown>;
      const { data: _omit, ...rest } = b;
      return { ...parsed, ...rest };
    } catch {
      return raw;
    }
  }
  return raw;
};

const repeatConfigBody = z
  .object({
    frequency: z.nativeEnum(RepeatFrequency).optional(),
    startDate: z.coerce.date().optional().nullable(),
    interval: z.coerce.number().int().min(1).optional(),
    unit: z.nativeEnum(RepeatUnit).optional().nullable(),
    weekDays: z.array(z.nativeEnum(WeekDay)).optional(),
    monthDay: z.coerce.number().int().min(1).max(31).optional().nullable(),
    monthWeek: z.nativeEnum(MonthWeek).optional().nullable(),
    monthWeekDay: z.nativeEnum(WeekDay).optional().nullable(),
    endType: z.nativeEnum(RepeatEndType).optional(),
    endDate: z.coerce.date().optional().nullable(),
    endAfterCount: z.coerce.number().int().min(1).optional().nullable(),
    timezone: z.string().max(80).optional().nullable(),
    nextAutoGenerateDate: z.coerce.date().optional().nullable(),
  })
  .optional()
  .nullable();

const eventRoundInput = z.object({
  roundType: z.nativeEnum(CompetitionLevel),
  deadline: z.coerce.date(),
  cost: z.union([z.string(), z.number()]),
  hasFinalDeadline: z.boolean().optional(),
  finalDeadline: z.coerce.date().optional().nullable(),
  lateFee: z.union([z.string(), z.number()]).optional(),
  description: z.string().max(2000).optional().nullable(),
});

const eventGroupInput = z.object({
  name: z.string().trim().min(1).max(200),
  criteria: z.nativeEnum(GroupCriteria),
  condition: z.nativeEnum(RoundCondition),
  value: z.coerce.number().int(),
  rounds: z.array(eventRoundInput).optional(),
});

const eventSessionInput = z
  .object({
    sessionId: z.string().min(1).optional(),
    year: z.string().trim().min(2).max(16).optional(),
    sessionIdentifier: z.string().trim().min(1).max(120).optional(),
    sessionBucketFormat: z.nativeEnum(SessionBucketFormat).optional(),
    bucketQuarter: z.coerce.number().int().min(1).max(4).optional().nullable(),
    bucketMonth: z.coerce.number().int().min(1).max(12).optional().nullable(),
    bucketDate: z.coerce.date().optional().nullable(),
    sessionNumber: z.coerce.number().int().min(1).optional(),
    competitionLevel: z.nativeEnum(CompetitionLevel),
    eventType: z.nativeEnum(EventType),
    registrationDate: z.coerce.date(),
    deadline: z.coerce.date(),
    cost: z.union([z.string(), z.number()]),
    hasFinalDeadline: z.boolean().optional(),
    finalDeadline: z.coerce.date().optional().nullable(),
    lateFee: z.union([z.string(), z.number()]).optional(),
    status: z.nativeEnum(SessionStatus).optional(),
    isSharedToCommunity: z.boolean().optional(),
    isUserAgreementAccepted: z.boolean().optional(),
    autoGenerated: z.boolean().optional(),
    /** At most one row in `eventSessions` should be true; if omitted, first session becomes current. */
    isCurrentSession: z.boolean().optional(),
    groups: z.array(eventGroupInput).optional(),
  })
  .superRefine((val, ctx) => {
    const hasSessionId = Boolean(val.sessionId);
    const hasNewSession = Boolean(val.year);
    if (hasSessionId === hasNewSession) {
      ctx.addIssue({
        code: 'custom',
        message:
          'Each eventSession must set exactly one of: sessionId (link existing Session) OR year (create Session).',
      });
    }
  });

const createEventBodySchema = z
  .object({
    eventName: z.string().trim().min(1).max(200),
    /** Omit when sending file `coverImage`; otherwise required URL (validated in service). */
    coverImage: z.string().min(1).optional(),
    programId: z.string().min(1),
    organizer: z.string().trim().min(1).max(200),
    location: z.string().trim().max(300).optional().nullable(),
    eventPortal: z.string().min(1),
    registrationPortal: z.string().min(1),
    description: z.string().min(1),
    note: z.string().max(2000).optional().nullable(),
    isPublished: z.coerce.boolean().optional(),
    repeatConfig: repeatConfigBody,
    eventSessions: z.array(eventSessionInput).optional(),
  })
  .superRefine((body, ctx) => {
    const sessions = body.eventSessions;
    if (!sessions?.length) return;
    const n = sessions.filter(s => s.isCurrentSession === true).length;
    if (n > 1) {
      ctx.addIssue({
        code: 'custom',
        message: 'At most one eventSession may set isCurrentSession to true.',
      });
    }
  });

const createEvent = z.object({
  body: z.preprocess(mergeEventFormDataField, createEventBodySchema),
});

const sessionScopeEnum = z.enum(['today', 'upcoming', 'history']);

const priceQuery = {
  priceMin: z.string().optional(),
  priceMax: z.string().optional(),
} as const;

const listEvents = z.object({
  query: z
    .object({
      search: z.string().optional(),
      programId: z.string().optional(),
      eventType: z.nativeEnum(EventType).optional(),
      location: z.string().optional(),
      groupCriteria: z.nativeEnum(GroupCriteria).optional(),
      timeRangeFrom: z.coerce.date().optional(),
      timeRangeTo: z.coerce.date().optional(),
      sessionScope: sessionScopeEnum.optional(),
      ...priceQuery,
      page: z.coerce.number().int().min(1).optional(),
      limit: z.coerce.number().int().min(1).max(100).optional(),
      sortBy: z.string().optional(),
      sortOrder: z.enum(['asc', 'desc']).optional(),
    })
    .refine(
      q =>
        !q.timeRangeFrom ||
        !q.timeRangeTo ||
        q.timeRangeFrom.getTime() <= q.timeRangeTo.getTime(),
      { message: 'timeRangeFrom must be before or equal to timeRangeTo.' }
    ),
});

const listFeed = z.object({
  query: z.object({
    page: z.coerce.number().int().min(1).optional(),
    limit: z.coerce.number().int().min(1).max(100).optional(),
    sortBy: z.string().optional(),
    sortOrder: z.enum(['asc', 'desc']).optional(),
    ...priceQuery,
  }),
});

const calendarMonthFeed = z.object({
  query: z.object({
    year: z.coerce.number().int().min(2000).max(2100),
    month: z.coerce.number().int().min(1).max(12),
    programId: z.string().optional(),
    ...priceQuery,
  }),
});

const calendarDayFeed = z.object({
  query: z.object({
    date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'date must be YYYY-MM-DD (UTC day)'),
    programId: z.string().optional(),
    ...priceQuery,
    page: z.coerce.number().int().min(1).optional(),
    limit: z.coerce.number().int().min(1).max(100).optional(),
    sortBy: z.string().optional(),
    sortOrder: z.enum(['asc', 'desc']).optional(),
  }),
});

const getEventById = z.object({
  params: eventIdParam,
});

const updateCurrentEventSessionBody = z.object({
  competitionLevel: z.nativeEnum(CompetitionLevel).optional(),
  eventType: z.nativeEnum(EventType).optional(),
  registrationDate: z.coerce.date().optional(),
  deadline: z.coerce.date().optional(),
  cost: z.union([z.string(), z.number()]).optional(),
  hasFinalDeadline: z.boolean().optional(),
  finalDeadline: z.coerce.date().optional().nullable(),
  lateFee: z.union([z.string(), z.number()]).optional(),
  status: z.nativeEnum(SessionStatus).optional(),
  isSharedToCommunity: z.boolean().optional(),
  isUserAgreementAccepted: z.boolean().optional(),
  autoGenerated: z.boolean().optional(),
});

const updateEventBodySchema = z
  .object({
    eventName: z.string().trim().min(1).max(200).optional(),
    coverImage: z.string().min(1).optional(),
    programId: z.string().min(1).optional(),
    organizer: z.string().trim().min(1).max(200).optional(),
    location: z.string().trim().max(300).optional().nullable(),
    eventPortal: z.string().min(1).optional(),
    registrationPortal: z.string().min(1).optional(),
    description: z.string().min(1).optional(),
    note: z.string().max(2000).optional().nullable(),
    isPublished: z.coerce.boolean().optional(),
    isActive: z.coerce.boolean().optional(),
    isLocked: z.coerce.boolean().optional(),
    repeatConfig: repeatConfigBody,
    currentEventSession: updateCurrentEventSessionBody.optional(),
  })
  .superRefine((data, ctx) => {
    const cs = data.currentEventSession;
    if (cs != null && typeof cs === 'object' && Object.keys(cs).length === 0) {
      ctx.addIssue({
        code: 'custom',
        message: 'currentEventSession cannot be an empty object; omit the key or send at least one field.',
      });
    }
  });

const updateEvent = z.object({
  params: eventIdParam,
  body: z.preprocess(mergeEventFormDataField, updateEventBodySchema),
});

const deleteEvent = z.object({
  params: eventIdParam,
});

const listEventSessions = z.object({
  params: eventIdParam,
});

const verifyEvent = z.object({
  params: eventIdParam,
});

const applyToEvent = z.object({
  params: eventIdParam,
  body: z
    .object({
      note: z.string().max(1000).optional().nullable(),
    })
    .default({}),
});

const withdrawApplication = z.object({
  params: eventIdParam,
});

const listEventApplications = z.object({
  params: eventIdParam,
});

export const EventValidation = {
  createEvent,
  listEvents,
  listFeed,
  calendarMonthFeed,
  calendarDayFeed,
  getEventById,
  updateEvent,
  deleteEvent,
  listEventSessions,
  verifyEvent,
  applyToEvent,
  withdrawApplication,
  listEventApplications,
};
