import logger from '../../config/logger';
import { database } from '../../config/database';
import { RepeatFrequency } from '../../../prisma/generated/enums';
import { EventRepository } from './event.repository';
import type { ICreateEventPayload, IEventGroupInput } from './event.interface';
import { addRepeatInterval, computeRepeatingEventNaming } from './event.utils';
import { enqueueRepeatEventJob } from '../../jobs/repeatEvent.schedule';

type RepeatSourceEvent = NonNullable<
  Awaited<ReturnType<typeof loadRepeatSourceEvent>>
>;

const loadRepeatSourceEvent = async (eventId: string) => {
  return database.event.findFirst({
    where: { id: eventId, deletedAt: null, isDeleted: false },
    select: {
      id: true,
      creatorId: true,
      eventName: true,
      baseEventName: true,
      coverImage: true,
      programId: true,
      organizer: true,
      location: true,
      eventPortal: true,
      registrationPortal: true,
      description: true,
      note: true,
      isPublished: true,
      isSharedToCommunity: true,
      isUserAgreementAccepted: true,
      repeatConfig: {
        select: {
          frequency: true,
          startDate: true,
          nextAutoGenerateDate: true,
        },
      },
      schedule: {
        select: {
          competitionLevel: true,
          eventType: true,
          registrationDate: true,
          deadline: true,
          cost: true,
          hasFinalDeadline: true,
          finalDeadline: true,
          lateFee: true,
        },
      },
      groups: {
        select: {
          name: true,
          criteria: true,
          condition: true,
          value: true,
          rounds: {
            select: {
              roundType: true,
              deadline: true,
              cost: true,
              hasFinalDeadline: true,
              finalDeadline: true,
              lateFee: true,
              description: true,
            },
          },
        },
      },
    },
  });
};

const mapGroupsWithShift = (
  source: RepeatSourceEvent,
  anchorDate: Date
): IEventGroupInput[] | undefined => {
  if (!source.groups.length || !source.schedule) return undefined;
  const baseRegistration = source.schedule.registrationDate.getTime();
  return source.groups.map(g => ({
    name: g.name,
    criteria: g.criteria,
    condition: g.condition,
    value: g.value,
    rounds: g.rounds.map(r => {
      const roundOffset = r.deadline.getTime() - baseRegistration;
      const finalOffset =
        r.finalDeadline != null ? r.finalDeadline.getTime() - baseRegistration : null;
      return {
        roundType: r.roundType,
        deadline: new Date(anchorDate.getTime() + roundOffset),
        cost: Number(r.cost),
        hasFinalDeadline: r.hasFinalDeadline,
        finalDeadline: finalOffset == null ? null : new Date(anchorDate.getTime() + finalOffset),
        lateFee: Number(r.lateFee),
        description: r.description ?? null,
      };
    }),
  }));
};

const buildClonePayload = (source: RepeatSourceEvent, anchorDate: Date): ICreateEventPayload => {
  if (!source.schedule || !source.repeatConfig) {
    throw new Error('Source event missing schedule or repeat configuration.');
  }
  const repeatFrequency = source.repeatConfig.frequency;
  const baseName = source.baseEventName?.trim() || source.eventName.trim();
  const naming = computeRepeatingEventNaming(
    baseName,
    anchorDate,
    repeatFrequency,
    source.repeatConfig.startDate ?? anchorDate
  );

  const scheduleDurationMs =
    source.schedule.deadline.getTime() - source.schedule.registrationDate.getTime();
  const finalDurationMs =
    source.schedule.finalDeadline != null
      ? source.schedule.finalDeadline.getTime() - source.schedule.registrationDate.getTime()
      : null;

  return {
    eventName: baseName,
    coverImage: source.coverImage,
    programId: source.programId,
    organizer: source.organizer,
    location: source.location,
    eventPortal: source.eventPortal,
    registrationPortal: source.registrationPortal,
    description: source.description,
    note: source.note,
    isPublished: source.isPublished,
    sessionId: undefined,
    year: naming.yearForEvent,
    session: naming.sessionTypeForEvent,
    sessionValue: naming.sessionValueForEvent,
    sessionLevel: naming.sessionLevelForEvent,
    isSharedToCommunity: source.isSharedToCommunity,
    isUserAgreementAccepted: source.isUserAgreementAccepted,
    groups: mapGroupsWithShift(source, anchorDate),
    schedule: {
      competitionLevel: source.schedule.competitionLevel,
      eventType: source.schedule.eventType,
      registrationDate: anchorDate,
      deadline: new Date(anchorDate.getTime() + scheduleDurationMs),
      cost: Number(source.schedule.cost),
      hasFinalDeadline: source.schedule.hasFinalDeadline,
      finalDeadline: finalDurationMs == null ? null : new Date(anchorDate.getTime() + finalDurationMs),
      lateFee: Number(source.schedule.lateFee),
    },
  };
};

export async function generateNextRepeatedEvent(sourceEventId: string): Promise<void> {
  const source = await loadRepeatSourceEvent(sourceEventId);
  if (!source) {
    logger.warn(`repeat-event source not found eventId=${sourceEventId}`);
    return;
  }
  if (!source.repeatConfig || !source.schedule) {
    logger.warn(`repeat-event source missing repeatConfig/schedule eventId=${sourceEventId}`);
    return;
  }
  if (source.repeatConfig.frequency === RepeatFrequency.DontRepeat) {
    logger.info(`repeat-event source is DontRepeat, skipping eventId=${sourceEventId}`);
    return;
  }

  const runAnchor = source.repeatConfig.nextAutoGenerateDate ?? new Date();
  const baseName = source.baseEventName?.trim() || source.eventName.trim();
  const naming = computeRepeatingEventNaming(
    baseName,
    runAnchor,
    source.repeatConfig.frequency,
    source.repeatConfig.startDate ?? runAnchor
  );

  const existing = await database.event.findFirst({
    where: {
      eventName: naming.eventNameWithSuffix,
      deletedAt: null,
      isDeleted: false,
    },
    select: { id: true },
  });

  if (!existing) {
    const payload = buildClonePayload(source, runAnchor);
    await EventRepository.createEvent(source.creatorId, payload);
    logger.info(
      `repeat-event cloned sourceEventId=${sourceEventId} generatedEventName=${naming.eventNameWithSuffix}`
    );
  } else {
    logger.warn(
      `repeat-event clone already exists sourceEventId=${sourceEventId} eventName=${naming.eventNameWithSuffix}`
    );
  }

  const nextRunAt = addRepeatInterval(runAnchor, source.repeatConfig.frequency);
  await database.repeatConfig.update({
    where: { eventId: sourceEventId },
    data: { nextAutoGenerateDate: nextRunAt },
  });
  await enqueueRepeatEventJob(sourceEventId, nextRunAt);
}
